add_executable(pic_llm_bench ${CMAKE_CURRENT_LIST_DIR}/llm_bench.cpp ${CMAKE_CURRENT_SOURCE_DIR}/tools/cpp/Profiler.cpp)
add_executable(pic_quantize_llm ${CMAKE_CURRENT_LIST_DIR}/quantize_llm.cpp)
add_executable(pic_ppl_eval ${CMAKE_CURRENT_LIST_DIR}/ppl_eval.cpp)
add_executable(pic_generateLlmIO ${CMAKE_CURRENT_LIST_DIR}/generateLlmIO.cpp)
target_link_libraries(pic_llm_bench ${LLM_DEPS})
target_include_directories(pic_llm_bench PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/tools/cpp)
target_link_libraries(pic_generateLlmIO ${LLM_DEPS})
target_link_libraries(pic_quantize_llm ${LLM_DEPS})
target_include_directories(pic_generateLlmIO PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../src)
target_include_directories(pic_quantize_llm PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../src)
target_link_libraries(pic_ppl_eval ${LLM_DEPS})
target_include_directories(pic_ppl_eval PRIVATE ${CMAKE_CURRENT_LIST_DIR}/../src)
