#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* paged_decode_attention_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"#define GLOBAL_SIZE_2_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,\n"
"#define DEAL_NON_UNIFORM_DIM2(input1, input2) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "" return; "" }\n"
"__kernel void transpose_paged_key_to_decode_key(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *key_cache,// [max_slots,batch,kv_head_num,head_dim]\n"
" __global FLOAT *decode_key,// [batch,kv_head_num,head_dim,max_slots]\n"
" __private const int batch,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim,\n"
" __private const int key_seq_len,\n"
" __private const int key_max_len) {\n"
" const int x=get_global_id(0); // logical\n"
" const int y=get_global_id(1); // batch*kv_head_num*head_dim\n"
" DEAL_NON_UNIFORM_DIM2(x,y);\n"
" const int logical=x;\n"
" const int d=y % head_dim;\n"
" const int tmp=y/head_dim;\n"
" const int kvh=tmp % kv_head_num;\n"
" const int b=tmp/kv_head_num;\n"
" if (b >= batch || logical >= key_seq_len) {\n"
" return;\n"
" }\n"
" const int slot=logical;\n"
" if (slot<0 || slot >= key_max_len) {\n"
" return;\n"
" }\n"
" const int src=((slot*batch+b)*kv_head_num+kvh)*head_dim+d;\n"
" const int dst=((b*kv_head_num+kvh)*head_dim+d)*key_max_len+logical;\n"
" decode_key[dst]=key_cache[src];\n"
"}\n"
"__kernel void append_decode_key_value_hd128(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *key,// [batch,1,kv_head_num,128]\n"
" __global const FLOAT *value,// [batch,1,kv_head_num,128]\n"
" __global FLOAT *key_cache,// [max_slots,batch,kv_head_num,128]\n"
" __global FLOAT *value_cache,// [batch,kv_head_num,max_slots,128]\n"
" __global FLOAT *decode_key,// [batch,kv_head_num,128,max_slots]\n"
" __private const int batch,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim,\n"
" __private const int q_index,\n"
" __private const int logical,\n"
" __private const int key_max_len) {\n"
" const int x=get_global_id(0); // head_dim\n"
" const int y=get_global_id(1); // batch*kv_head_num\n"
" DEAL_NON_UNIFORM_DIM2(x,y);\n"
" if (head_dim != 128 || logical<0 || logical >= key_max_len) {\n"
" return;\n"
" }\n"
" const int d=x;\n"
" const int b=y/kv_head_num;\n"
" const int kvh=y-b*kv_head_num;\n"
" if (b >= batch || kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" const int in=((b+0)*kv_head_num+kvh)*128+d+q_index*kv_head_num*128;\n"
" const FLOAT k=key[in];\n"
" const FLOAT v=value[in];\n"
" const int slot=logical;\n"
" if (slot<0 || slot >= key_max_len) {\n"
" return;\n"
" }\n"
" key_cache[((slot*batch+b)*kv_head_num+kvh)*128+d]=k;\n"
" value_cache[((b*kv_head_num+kvh)*key_max_len+slot)*128+d]=v;\n"
" decode_key[((b*kv_head_num+kvh)*128+d)*key_max_len+logical]=k;\n"
"}\n"
"__kernel void append_sparse_decode_key_value_hd128(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *key,// [batch,new_kv_len,kv_head_num,128]\n"
" __global const FLOAT *value,// [batch,new_kv_len,kv_head_num,128]\n"
" __global FLOAT *key_cache,// [max_slots,batch,kv_head_num,128]\n"
" __global FLOAT *value_cache,// [batch,kv_head_num,max_slots,128]\n"
" __global FLOAT *decode_key,// [batch,kv_head_num,128,max_slots]\n"
" __global const int *sparse_query,\n"
" __private const int batch,\n"
" __private const int new_kv_len,\n"
" __private const int kv_write_len,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim,\n"
" __private const int key_max_len) {\n"
" const int d=get_global_id(0);\n"
" const int l=get_global_id(1);\n"
" const int z=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(d,l,z);\n"
" if (head_dim != 128 || d >= 128 || l >= kv_write_len || l >= new_kv_len) {\n"
" return;\n"
" }\n"
" const int b=z/kv_head_num;\n"
" const int kvh=z-b*kv_head_num;\n"
" if (b >= batch || kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" const int logical=sparse_query[l];\n"
" if (logical<0 || logical >= key_max_len) {\n"
" return;\n"
" }\n"
" const int slot=logical;\n"
" if (slot<0 || slot >= key_max_len) {\n"
" return;\n"
" }\n"
" const int in=((b*new_kv_len+l)*kv_head_num+kvh)*128+d;\n"
" const FLOAT k=key[in];\n"
" const FLOAT v=value[in];\n"
" key_cache[((slot*batch+b)*kv_head_num+kvh)*128+d]=k;\n"
" value_cache[((b*kv_head_num+kvh)*key_max_len+slot)*128+d]=v;\n"
" decode_key[((b*kv_head_num+kvh)*128+d)*key_max_len+logical]=k;\n"
"}\n"
"__kernel void matmul_qk_decode_transposed_hd128(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *query,// [batch,query_seq_len,head_num,128]\n"
" __global const FLOAT *decode_key,// [batch,kv_head_num,128,max_slots]\n"
" __global FLOAT *qk,// [batch*head_num,key_seq_len]\n"
" __private const float scale,\n"
" __private const int batch,\n"
" __private const int query_seq_len,\n"
" __private const int key_seq_len,\n"
" __private const int key_max_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // key_seq_len/4\n"
" const int y=get_global_id(1); // batch*head_num\n"
" DEAL_NON_UNIFORM_DIM2(x,y);\n"
" if (head_dim != 128) {\n"
" return;\n"
" }\n"
" const int x4=x << 2;\n"
" const int b=y/head_num;\n"
" const int h=y-b*head_num;\n"
" const int kvh=h/NUMHEAD_GROUP_SIZE;\n"
" if (b >= batch || kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" const int query_offset=(b*query_seq_len*head_num+h)*128;\n"
" const int key_base=((b*kv_head_num+kvh)*128)*key_max_len;\n"
" COMPUTE_FLOAT4 out0=(COMPUTE_FLOAT4)0;\n"
" if (x4+3<key_seq_len) {\n"
" for (int d=0; d<128; ++d) {\n"
" const COMPUTE_FLOAT qv=(COMPUTE_FLOAT)query[query_offset+d];\n"
" const COMPUTE_FLOAT4 kv=CONVERT_COMPUTE_FLOAT4(vload4(0,decode_key+key_base+d*key_max_len+x4));\n"
" out0=mad((COMPUTE_FLOAT4)qv,kv,out0);\n"
" }\n"
" out0 *= (COMPUTE_FLOAT4)scale;\n"
" vstore4(CONVERT_FLOAT4(out0),0,qk+y*key_seq_len+x4);\n"
" return;\n"
" }\n"
" for (int d=0; d<128; ++d) {\n"
" const COMPUTE_FLOAT qv=(COMPUTE_FLOAT)query[query_offset+d];\n"
" if (x4<key_seq_len) {\n"
" out0.s0 += qv*(COMPUTE_FLOAT)decode_key[key_base+d*key_max_len+x4];\n"
" }\n"
" if (x4+1<key_seq_len) {\n"
" out0.s1 += qv*(COMPUTE_FLOAT)decode_key[key_base+d*key_max_len+x4+1];\n"
" }\n"
" if (x4+2<key_seq_len) {\n"
" out0.s2 += qv*(COMPUTE_FLOAT)decode_key[key_base+d*key_max_len+x4+2];\n"
" }\n"
" }\n"
" out0 *= (COMPUTE_FLOAT4)scale;\n"
" const int qk_offset=y*key_seq_len+x4;\n"
" if (x4+2<key_seq_len) {\n"
" vstore3(CONVERT_FLOAT3((COMPUTE_FLOAT3)(out0.s012)),0,qk+qk_offset);\n"
" } else if (x4+1<key_seq_len) {\n"
" vstore2(CONVERT_FLOAT2((COMPUTE_FLOAT2)(out0.s01)),0,qk+qk_offset);\n"
" } else if (x4<key_seq_len) {\n"
" qk[qk_offset]=(FLOAT)out0.s0;\n"
" }\n"
"}\n"
"__kernel void matmul_qkv_decode_value_hd128_b8(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *qk,// [batch*head_num,qk_seq_len]\n"
" __global const FLOAT *value_cache,// [batch,kv_head_num,max_slots,128]\n"
" __global FLOAT *output,// [batch,1,head_num,128]\n"
" __private const int qk_seq_len,\n"
" __private const int max_len,\n"
" __private const int batch,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // head_dim/8\n"
" const int y=get_global_id(1); // batch*head_num\n"
" DEAL_NON_UNIFORM_DIM2(x,y);\n"
" if (head_dim != 128) {\n"
" return;\n"
" }\n"
" const int x8=x << 3;\n"
" const int b=y/head_num;\n"
" const int h=y-b*head_num;\n"
" const int kvh=h/NUMHEAD_GROUP_SIZE;\n"
" if (b >= batch || kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" const int qk_offset=y*qk_seq_len;\n"
" const int value_offset=((b*kv_head_num+kvh)*max_len)*128+x8;\n"
" COMPUTE_FLOAT8 out0=(COMPUTE_FLOAT8)0;\n"
" const int loop_end=max((qk_seq_len+7)/8-1,0);\n"
" for (int i=0; i<loop_end; ++i) {\n"
" const int i8=i << 3;\n"
" const COMPUTE_FLOAT8 w=CONVERT_COMPUTE_FLOAT8(vload8(0,qk+qk_offset+i8));\n"
" out0=mad((COMPUTE_FLOAT8)w.s0,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+(i8+0)*128)),out0);\n"
" out0=mad((COMPUTE_FLOAT8)w.s1,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+(i8+1)*128)),out0);\n"
" out0=mad((COMPUTE_FLOAT8)w.s2,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+(i8+2)*128)),out0);\n"
" out0=mad((COMPUTE_FLOAT8)w.s3,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+(i8+3)*128)),out0);\n"
" out0=mad((COMPUTE_FLOAT8)w.s4,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+(i8+4)*128)),out0);\n"
" out0=mad((COMPUTE_FLOAT8)w.s5,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+(i8+5)*128)),out0);\n"
" out0=mad((COMPUTE_FLOAT8)w.s6,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+(i8+6)*128)),out0);\n"
" out0=mad((COMPUTE_FLOAT8)w.s7,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+(i8+7)*128)),out0);\n"
" }\n"
" for (int i=(loop_end << 3); i<qk_seq_len; ++i) {\n"
" const COMPUTE_FLOAT w=(COMPUTE_FLOAT)qk[qk_offset+i];\n"
" out0=mad((COMPUTE_FLOAT8)w,CONVERT_COMPUTE_FLOAT8(vload8(0,value_cache+value_offset+i*128)),out0);\n"
" }\n"
" vstore8(CONVERT_FLOAT8(out0),0,output+y*128+x8);\n"
"}\n"
"__kernel void matmul_qk_decode_paged_identity_hd128(GLOBAL_SIZE_2_DIMS\n"
" __global const FLOAT *query,// [batch,query_seq_len,head_num,128]\n"
" __global const FLOAT *key_cache,// [max_slots,batch,kv_head_num,128]\n"
" __global FLOAT *qk,// [batch*head_num,key_seq_len]\n"
" __private const float scale,\n"
" __private const int batch,\n"
" __private const int query_seq_len,\n"
" __private const int key_seq_len,\n"
" __private const int key_max_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // key_seq_len/4\n"
" const int y=get_global_id(1); // batch*head_num\n"
" DEAL_NON_UNIFORM_DIM2(x,y);\n"
" if (head_dim != 128) {\n"
" return;\n"
" }\n"
" const int x4=x << 2;\n"
" const int b=y/head_num;\n"
" const int h=y-b*head_num;\n"
" const int kvh=h/NUMHEAD_GROUP_SIZE;\n"
" const int query_offset=((b*query_seq_len)*head_num+h)*128;\n"
" COMPUTE_FLOAT4 out0=(COMPUTE_FLOAT4)0;\n"
" for (int d4=0; d4<128; d4 += 4) {\n"
" COMPUTE_FLOAT4 qv=CONVERT_COMPUTE_FLOAT4(vload4(0,query+query_offset+d4));\n"
" if (x4<key_seq_len) {\n"
" const int key_offset0=(((x4*batch+b)*kv_head_num+kvh)*128+d4);\n"
" COMPUTE_FLOAT4 kv0=CONVERT_COMPUTE_FLOAT4(vload4(0,key_cache+key_offset0));\n"
" out0.s0 += dot(qv,kv0);\n"
" }\n"
" if (x4+1<key_seq_len) {\n"
" const int key_offset1=((((x4+1)*batch+b)*kv_head_num+kvh)*128+d4);\n"
" COMPUTE_FLOAT4 kv1=CONVERT_COMPUTE_FLOAT4(vload4(0,key_cache+key_offset1));\n"
" out0.s1 += dot(qv,kv1);\n"
" }\n"
" if (x4+2<key_seq_len) {\n"
" const int key_offset2=((((x4+2)*batch+b)*kv_head_num+kvh)*128+d4);\n"
" COMPUTE_FLOAT4 kv2=CONVERT_COMPUTE_FLOAT4(vload4(0,key_cache+key_offset2));\n"
" out0.s2 += dot(qv,kv2);\n"
" }\n"
" if (x4+3<key_seq_len) {\n"
" const int key_offset3=((((x4+3)*batch+b)*kv_head_num+kvh)*128+d4);\n"
" COMPUTE_FLOAT4 kv3=CONVERT_COMPUTE_FLOAT4(vload4(0,key_cache+key_offset3));\n"
" out0.s3 += dot(qv,kv3);\n"
" }\n"
" }\n"
" out0 *= (COMPUTE_FLOAT4)scale;\n"
" const int qk_offset=y*key_seq_len+x4;\n"
" if (x4+3<key_seq_len) {\n"
" vstore4(CONVERT_FLOAT4(out0),0,qk+qk_offset);\n"
" } else if (x4+2<key_seq_len) {\n"
" vstore3(CONVERT_FLOAT3((COMPUTE_FLOAT3)(out0.s012)),0,qk+qk_offset);\n"
" } else if (x4+1<key_seq_len) {\n"
" vstore2(CONVERT_FLOAT2((COMPUTE_FLOAT2)(out0.s01)),0,qk+qk_offset);\n"
" } else if (x4<key_seq_len) {\n"
" qk[qk_offset]=(FLOAT)out0.s0;\n"
" }\n"
"}\n"
"#define DEFINE_DECODE_CAUSAL_IDENTITY_HD128(KERNEL_NAME, LANES) ""__kernel void KERNEL_NAME(GLOBAL_SIZE_3_DIMS "" __global const FLOAT *query, "" __global const FLOAT *key_cache, "" __global const FLOAT *value_cache, "" __global FLOAT *output, "" __private const float scale, "" __private const int batch, "" __private const int query_seq_len, "" __private const int output_seq_len, "" __private const int base_logical, "" __private const int key_seq_len, "" __private const int key_max_len, "" __private const int head_num, "" __private const int kv_head_num, "" __private const int head_dim) { "" const int x = get_global_id(0); "" const int y = get_global_id(1); "" int z = get_global_id(2); "" DEAL_NON_UNIFORM_DIM3(x, y, z); "" const int lid = get_local_id(0); "" if (get_local_size(0) != LANES || lid >= LANES || head_dim != 128) { "" return; "" } "" const int q_index = y; "" if (q_index >= output_seq_len) { "" return; "" } "" const int b = z / head_num; "" const int h = z - b * head_num; "" if (b >= batch) { "" return; "" } "" const int kvh = h / NUMHEAD_GROUP_SIZE; "" if (kvh >= kv_head_num) { "" return; "" } "" const int q_logical = base_logical + q_index; "" const int q_row = q_index; "" if (q_row < 0 || q_row >= query_seq_len) { "" return; "" } "" const int active_kv_seq_len = min(clamp(q_logical + 1, 0, key_seq_len), key_max_len); "" COMPUTE_FLOAT local local_q[128]; "" COMPUTE_FLOAT local score_tile[LANES]; "" COMPUTE_FLOAT local reduce[LANES]; "" const int out_d4 = lid << 2; "" COMPUTE_FLOAT4 out4 = (COMPUTE_FLOAT4)0; "" for (int d = lid; d < 128; d += LANES) { "" const int query_offset = ((b * query_seq_len + q_row) * head_num + h) * 128 + d; "" local_q[d] = (COMPUTE_FLOAT)query[query_offset]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" COMPUTE_FLOAT running_m = (COMPUTE_FLOAT)-FLT_MAX; "" COMPUTE_FLOAT running_l = (COMPUTE_FLOAT)0; "" for (int k_start = 0; k_start < active_kv_seq_len; k_start += LANES) { "" const int tile_count = min(LANES, active_kv_seq_len - k_start); "" COMPUTE_FLOAT score = (COMPUTE_FLOAT)-FLT_MAX; "" if (lid < tile_count) { "" const int k = k_start + lid; "" const int key_offset = ((k * batch + b) * kv_head_num + kvh) * 128; "" score = (COMPUTE_FLOAT)0; "" for (int d4 = 0; d4 < 128; d4 += 4) { "" COMPUTE_FLOAT4 qv = (COMPUTE_FLOAT4)(local_q[d4], local_q[d4 + 1], local_q[d4 + 2], local_q[d4 + 3]); "" COMPUTE_FLOAT4 kv = CONVERT_COMPUTE_FLOAT4(vload4(0, key_cache + key_offset + d4)); "" score += dot(qv, kv); "" } "" score *= (COMPUTE_FLOAT)scale; "" } "" score_tile[lid] = score; "" reduce[lid] = score; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] = fmax(reduce[lid], reduce[lid + stride]); "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_m = reduce[0]; "" COMPUTE_FLOAT tile_l_part = (COMPUTE_FLOAT)0; "" if (lid < tile_count && tile_m != (COMPUTE_FLOAT)-FLT_MAX) { "" tile_l_part = exp(score_tile[lid] - tile_m); "" } "" score_tile[lid] = tile_l_part; "" reduce[lid] = tile_l_part; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] += reduce[lid + stride]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_l = reduce[0]; "" if (tile_l > (COMPUTE_FLOAT)0) { "" const COMPUTE_FLOAT new_m = running_l > (COMPUTE_FLOAT)0 ? fmax(running_m, tile_m) : tile_m; "" const COMPUTE_FLOAT old_scale = running_l > (COMPUTE_FLOAT)0 ? exp(running_m - new_m) : (COMPUTE_FLOAT)0; "" const COMPUTE_FLOAT tile_scale = exp(tile_m - new_m); "" if (lid < 32) { "" COMPUTE_FLOAT4 tile_out4 = (COMPUTE_FLOAT4)0; "" for (int kk = 0; kk < tile_count; ++kk) { "" const COMPUTE_FLOAT tile_weight = score_tile[kk]; "" if (tile_weight == (COMPUTE_FLOAT)0) { "" continue; "" } "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + (k_start + kk)) * 128 + out_d4; "" tile_out4 += (COMPUTE_FLOAT4)tile_weight * CONVERT_COMPUTE_FLOAT4(vload4(0, value_cache + value_offset)); "" } "" out4 = out4 * (COMPUTE_FLOAT4)old_scale + tile_out4 * (COMPUTE_FLOAT4)tile_scale; "" } "" running_l = running_l * old_scale + tile_l * tile_scale; "" running_m = new_m; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT inv_l = running_l > (COMPUTE_FLOAT)0 ? (COMPUTE_FLOAT)1 / running_l : (COMPUTE_FLOAT)0; "" const int output_offset = ((b * output_seq_len + q_index) * head_num + h) * 128; "" if (lid < 32) { "" vstore4(CONVERT_FLOAT4(out4 * (COMPUTE_FLOAT4)inv_l), 0, output + output_offset + out_d4); "" } ""}\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_HD128(decode_causal_attention_hd128_identity_row32,32)\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_HD128(decode_causal_attention_hd128_identity_row64,64)\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_HD128(decode_causal_attention_hd128_identity_row128,128)\n"
"#define DEFINE_DECODE_CAUSAL_IDENTITY_FUSED_KV_HD128(KERNEL_NAME, LANES) ""__kernel void KERNEL_NAME(GLOBAL_SIZE_3_DIMS "" __global const FLOAT *query, "" __global const FLOAT *key, "" __global const FLOAT *value, "" __global FLOAT *key_cache, "" __global FLOAT *value_cache, "" __global FLOAT *output, "" __private const float scale, "" __private const int batch, "" __private const int query_seq_len, "" __private const int output_seq_len, "" __private const int base_logical, "" __private const int key_seq_len, "" __private const int key_max_len, "" __private const int head_num, "" __private const int kv_head_num, "" __private const int head_dim) { "" const int x = get_global_id(0); "" const int y = get_global_id(1); "" int z = get_global_id(2); "" DEAL_NON_UNIFORM_DIM3(x, y, z); "" const int lid = get_local_id(0); "" if (get_local_size(0) != LANES || lid >= LANES || head_dim != 128) { "" return; "" } "" const int q_index = y; "" if (q_index >= output_seq_len) { "" return; "" } "" const int b = z / head_num; "" const int h = z - b * head_num; "" if (b >= batch) { "" return; "" } "" const int kvh = h / NUMHEAD_GROUP_SIZE; "" if (kvh >= kv_head_num) { "" return; "" } "" const int q_logical = base_logical + q_index; "" const int q_row = q_index; "" if (q_row < 0 || q_row >= query_seq_len || q_logical < 0 || q_logical >= key_max_len) { "" return; "" } "" for (int d = lid; d < 128; d += LANES) { "" const int in_offset = ((b * output_seq_len + q_index) * kv_head_num + kvh) * 128 + d; "" const int key_offset = ((q_logical * batch + b) * kv_head_num + kvh) * 128 + d; "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + q_logical) * 128 + d; "" key_cache[key_offset] = key[in_offset]; "" value_cache[value_offset] = value[in_offset]; "" } "" barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE); "" const int active_kv_seq_len = min(clamp(q_logical + 1, 0, key_seq_len), key_max_len); "" COMPUTE_FLOAT local local_q[128]; "" COMPUTE_FLOAT local score_tile[LANES]; "" COMPUTE_FLOAT local reduce[LANES]; "" const int out_d4 = lid << 2; "" COMPUTE_FLOAT4 out4 = (COMPUTE_FLOAT4)0; "" for (int d = lid; d < 128; d += LANES) { "" const int query_offset = ((b * query_seq_len + q_row) * head_num + h) * 128 + d; "" local_q[d] = (COMPUTE_FLOAT)query[query_offset]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" COMPUTE_FLOAT running_m = (COMPUTE_FLOAT)-FLT_MAX; "" COMPUTE_FLOAT running_l = (COMPUTE_FLOAT)0; "" for (int k_start = 0; k_start < active_kv_seq_len; k_start += LANES) { "" const int tile_count = min(LANES, active_kv_seq_len - k_start); "" COMPUTE_FLOAT score = (COMPUTE_FLOAT)-FLT_MAX; "" if (lid < tile_count) { "" const int k = k_start + lid; "" const int key_offset = ((k * batch + b) * kv_head_num + kvh) * 128; "" score = (COMPUTE_FLOAT)0; "" for (int d4 = 0; d4 < 128; d4 += 4) { "" COMPUTE_FLOAT4 qv = (COMPUTE_FLOAT4)(local_q[d4], local_q[d4 + 1], local_q[d4 + 2], local_q[d4 + 3]); "" COMPUTE_FLOAT4 kv = CONVERT_COMPUTE_FLOAT4(vload4(0, key_cache + key_offset + d4)); "" score += dot(qv, kv); "" } "" score *= (COMPUTE_FLOAT)scale; "" } "" score_tile[lid] = score; "" reduce[lid] = score; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] = fmax(reduce[lid], reduce[lid + stride]); "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_m = reduce[0]; "" COMPUTE_FLOAT tile_l_part = (COMPUTE_FLOAT)0; "" if (lid < tile_count && tile_m != (COMPUTE_FLOAT)-FLT_MAX) { "" tile_l_part = exp(score_tile[lid] - tile_m); "" } "" score_tile[lid] = tile_l_part; "" reduce[lid] = tile_l_part; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] += reduce[lid + stride]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_l = reduce[0]; "" if (tile_l > (COMPUTE_FLOAT)0) { "" const COMPUTE_FLOAT new_m = running_l > (COMPUTE_FLOAT)0 ? fmax(running_m, tile_m) : tile_m; "" const COMPUTE_FLOAT old_scale = running_l > (COMPUTE_FLOAT)0 ? exp(running_m - new_m) : (COMPUTE_FLOAT)0; "" const COMPUTE_FLOAT tile_scale = exp(tile_m - new_m); "" if (lid < 32) { "" COMPUTE_FLOAT4 tile_out4 = (COMPUTE_FLOAT4)0; "" for (int kk = 0; kk < tile_count; ++kk) { "" const COMPUTE_FLOAT tile_weight = score_tile[kk]; "" if (tile_weight == (COMPUTE_FLOAT)0) { "" continue; "" } "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + (k_start + kk)) * 128 + out_d4; "" tile_out4 += (COMPUTE_FLOAT4)tile_weight * CONVERT_COMPUTE_FLOAT4(vload4(0, value_cache + value_offset)); "" } "" out4 = out4 * (COMPUTE_FLOAT4)old_scale + tile_out4 * (COMPUTE_FLOAT4)tile_scale; "" } "" running_l = running_l * old_scale + tile_l * tile_scale; "" running_m = new_m; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT inv_l = running_l > (COMPUTE_FLOAT)0 ? (COMPUTE_FLOAT)1 / running_l : (COMPUTE_FLOAT)0; "" const int output_offset = ((b * output_seq_len + q_index) * head_num + h) * 128; "" if (lid < 32) { "" vstore4(CONVERT_FLOAT4(out4 * (COMPUTE_FLOAT4)inv_l), 0, output + output_offset + out_d4); "" } ""}\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_FUSED_KV_HD128(decode_causal_attention_hd128_identity_fused_kv_row32,32)\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_FUSED_KV_HD128(decode_causal_attention_hd128_identity_fused_kv_row64,64)\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_FUSED_KV_HD128(decode_causal_attention_hd128_identity_fused_kv_row128,128)\n"
"#define DEFINE_DECODE_CAUSAL_TRANSPOSED_K_FUSED_KV_HD128(KERNEL_NAME, LANES) ""__kernel void KERNEL_NAME(GLOBAL_SIZE_3_DIMS "" __global const FLOAT *query, "" __global const FLOAT *key, "" __global const FLOAT *value, "" __global FLOAT *key_cache, "" __global FLOAT *value_cache, "" __global FLOAT *decode_key, """" __global FLOAT *output, "" __private const float scale, "" __private const int batch, "" __private const int query_seq_len, "" __private const int output_seq_len, "" __private const int base_logical, "" __private const int key_seq_len, "" __private const int key_max_len, "" __private const int head_num, "" __private const int kv_head_num, "" __private const int head_dim) { "" const int x = get_global_id(0); "" const int y = get_global_id(1); "" int z = get_global_id(2); "" DEAL_NON_UNIFORM_DIM3(x, y, z); "" const int lid = get_local_id(0); "" if (get_local_size(0) != LANES || lid >= LANES || head_dim != 128) { "" return; "" } "" const int q_index = y; "" if (q_index >= output_seq_len) { "" return; "" } "" const int b = z / head_num; "" const int h = z - b * head_num; "" if (b >= batch) { "" return; "" } "" const int kvh = h / NUMHEAD_GROUP_SIZE; "" if (kvh >= kv_head_num) { "" return; "" } "" const int q_logical = base_logical + q_index; "" const int q_row = q_index; "" if (q_row < 0 || q_row >= query_seq_len || q_logical < 0 || q_logical >= key_max_len) { "" return; "" } "" const int q_slot = q_logical; "" if (q_slot < 0 || q_slot >= key_max_len) { "" return; "" } "" const int decode_key_base = ((b * kv_head_num + kvh) * 128) * key_max_len; "" for (int d = lid; d < 128; d += LANES) { "" const int in_offset = ((b * output_seq_len + q_index) * kv_head_num + kvh) * 128 + d; "" const FLOAT k = key[in_offset]; "" const FLOAT v = value[in_offset]; "" key_cache[((q_slot * batch + b) * kv_head_num + kvh) * 128 + d] = k; "" value_cache[((b * kv_head_num + kvh) * key_max_len + q_slot) * 128 + d] = v; "" decode_key[decode_key_base + d * key_max_len + q_logical] = k; "" } "" barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE); "" const int active_kv_seq_len = min(clamp(q_logical + 1, 0, key_seq_len), key_max_len); "" COMPUTE_FLOAT local local_q[128]; "" COMPUTE_FLOAT local score_tile[LANES]; "" COMPUTE_FLOAT local reduce[LANES]; "" const int out_d4 = lid << 2; "" COMPUTE_FLOAT4 out4 = (COMPUTE_FLOAT4)0; "" for (int d = lid; d < 128; d += LANES) { "" const int query_offset = ((b * query_seq_len + q_row) * head_num + h) * 128 + d; "" local_q[d] = (COMPUTE_FLOAT)query[query_offset]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" COMPUTE_FLOAT running_m = (COMPUTE_FLOAT)-FLT_MAX; "" COMPUTE_FLOAT running_l = (COMPUTE_FLOAT)0; "" for (int k_start = 0; k_start < active_kv_seq_len; k_start += LANES) { "" const int tile_count = min(LANES, active_kv_seq_len - k_start); "" COMPUTE_FLOAT score = (COMPUTE_FLOAT)-FLT_MAX; "" if (lid < tile_count) { "" const int k = k_start + lid; "" score = (COMPUTE_FLOAT)0; "" for (int d4 = 0; d4 < 128; d4 += 4) { "" COMPUTE_FLOAT4 qv = (COMPUTE_FLOAT4)(local_q[d4], local_q[d4 + 1], local_q[d4 + 2], local_q[d4 + 3]); "" COMPUTE_FLOAT4 kv = (COMPUTE_FLOAT4)( "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 0) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 1) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 2) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 3) * key_max_len + k]); "" score += dot(qv, kv); "" } "" score *= (COMPUTE_FLOAT)scale; "" } "" score_tile[lid] = score; "" reduce[lid] = score; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] = fmax(reduce[lid], reduce[lid + stride]); "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_m = reduce[0]; "" COMPUTE_FLOAT tile_l_part = (COMPUTE_FLOAT)0; "" if (lid < tile_count && tile_m != (COMPUTE_FLOAT)-FLT_MAX) { "" tile_l_part = exp(score_tile[lid] - tile_m); "" } "" score_tile[lid] = tile_l_part; "" reduce[lid] = tile_l_part; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] += reduce[lid + stride]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_l = reduce[0]; "" if (tile_l > (COMPUTE_FLOAT)0) { "" const COMPUTE_FLOAT new_m = running_l > (COMPUTE_FLOAT)0 ? fmax(running_m, tile_m) : tile_m; "" const COMPUTE_FLOAT old_scale = running_l > (COMPUTE_FLOAT)0 ? exp(running_m - new_m) : (COMPUTE_FLOAT)0; "" const COMPUTE_FLOAT tile_scale = exp(tile_m - new_m); "" if (lid < 32) { "" COMPUTE_FLOAT4 tile_out4 = (COMPUTE_FLOAT4)0; "" for (int kk = 0; kk < tile_count; ++kk) { "" const COMPUTE_FLOAT tile_weight = score_tile[kk]; "" if (tile_weight == (COMPUTE_FLOAT)0) { "" continue; "" } "" const int value_slot = k_start + kk; "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + value_slot) * 128 + out_d4; "" tile_out4 += (COMPUTE_FLOAT4)tile_weight * CONVERT_COMPUTE_FLOAT4(vload4(0, value_cache + value_offset)); "" } "" out4 = out4 * (COMPUTE_FLOAT4)old_scale + tile_out4 * (COMPUTE_FLOAT4)tile_scale; "" } "" running_l = running_l * old_scale + tile_l * tile_scale; "" running_m = new_m; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT inv_l = running_l > (COMPUTE_FLOAT)0 ? (COMPUTE_FLOAT)1 / running_l : (COMPUTE_FLOAT)0; "" const int output_offset = ((b * output_seq_len + q_index) * head_num + h) * 128; "" if (lid < 32) { "" vstore4(CONVERT_FLOAT4(out4 * (COMPUTE_FLOAT4)inv_l), 0, output + output_offset + out_d4); "" } ""}\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_FUSED_KV_HD128(decode_causal_attention_hd128_transposed_k_fused_kv_row32,32)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_FUSED_KV_HD128(decode_causal_attention_hd128_transposed_k_fused_kv_row64,64)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_FUSED_KV_HD128(decode_causal_attention_hd128_transposed_k_fused_kv_row128,128)\n"
"#define DEFINE_DECODE_CAUSAL_TRANSPOSED_K_READONLY_HD128(KERNEL_NAME, LANES) ""__kernel void KERNEL_NAME(GLOBAL_SIZE_3_DIMS "" __global const FLOAT *query, "" __global const FLOAT *value_cache, "" __global const FLOAT *decode_key, "" __global FLOAT *output, "" __private const float scale, "" __private const int batch, "" __private const int query_seq_len, "" __private const int output_seq_len, "" __private const int base_logical, "" __private const int key_seq_len, "" __private const int key_max_len, "" __private const int head_num, "" __private const int kv_head_num, "" __private const int head_dim) { "" const int x = get_global_id(0); "" const int y = get_global_id(1); "" int z = get_global_id(2); "" DEAL_NON_UNIFORM_DIM3(x, y, z); "" const int lid = get_local_id(0); "" if (get_local_size(0) != LANES || lid >= LANES || head_dim != 128) { "" return; "" } "" const int q_index = y; "" if (q_index >= output_seq_len) { "" return; "" } "" const int b = z / head_num; "" const int h = z - b * head_num; "" if (b >= batch) { "" return; "" } "" const int kvh = h / NUMHEAD_GROUP_SIZE; "" if (kvh >= kv_head_num) { "" return; "" } "" const int q_logical = base_logical + q_index; "" const int q_row = q_index; "" if (q_row < 0 || q_row >= query_seq_len || q_logical < 0 || q_logical >= key_max_len) { "" return; "" } "" const int active_kv_seq_len = min(clamp(q_logical + 1, 0, key_seq_len), key_max_len); "" const int decode_key_base = ((b * kv_head_num + kvh) * 128) * key_max_len; "" COMPUTE_FLOAT local local_q[128]; "" COMPUTE_FLOAT local score_tile[LANES]; "" COMPUTE_FLOAT local reduce[LANES]; "" const int out_d4 = lid << 2; "" COMPUTE_FLOAT4 out4 = (COMPUTE_FLOAT4)0; "" for (int d = lid; d < 128; d += LANES) { "" const int query_offset = ((b * query_seq_len + q_row) * head_num + h) * 128 + d; "" local_q[d] = (COMPUTE_FLOAT)query[query_offset]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" COMPUTE_FLOAT running_m = (COMPUTE_FLOAT)-FLT_MAX; "" COMPUTE_FLOAT running_l = (COMPUTE_FLOAT)0; "" for (int k_start = 0; k_start < active_kv_seq_len; k_start += LANES) { "" const int tile_count = min(LANES, active_kv_seq_len - k_start); "" COMPUTE_FLOAT score = (COMPUTE_FLOAT)-FLT_MAX; "" if (lid < tile_count) { "" const int k = k_start + lid; "" score = (COMPUTE_FLOAT)0; "" for (int d4 = 0; d4 < 128; d4 += 4) { "" COMPUTE_FLOAT4 qv = (COMPUTE_FLOAT4)(local_q[d4], local_q[d4 + 1], local_q[d4 + 2], local_q[d4 + 3]); "" COMPUTE_FLOAT4 kv = (COMPUTE_FLOAT4)( "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 0) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 1) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 2) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 3) * key_max_len + k]); "" score += dot(qv, kv); "" } "" score *= (COMPUTE_FLOAT)scale; "" } "" score_tile[lid] = score; "" reduce[lid] = score; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] = fmax(reduce[lid], reduce[lid + stride]); "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_m = reduce[0]; "" COMPUTE_FLOAT tile_l_part = (COMPUTE_FLOAT)0; "" if (lid < tile_count && tile_m != (COMPUTE_FLOAT)-FLT_MAX) { "" tile_l_part = exp(score_tile[lid] - tile_m); "" } "" score_tile[lid] = tile_l_part; "" reduce[lid] = tile_l_part; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] += reduce[lid + stride]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_l = reduce[0]; "" if (tile_l > (COMPUTE_FLOAT)0) { "" const COMPUTE_FLOAT new_m = running_l > (COMPUTE_FLOAT)0 ? fmax(running_m, tile_m) : tile_m; "" const COMPUTE_FLOAT old_scale = running_l > (COMPUTE_FLOAT)0 ? exp(running_m - new_m) : (COMPUTE_FLOAT)0; "" const COMPUTE_FLOAT tile_scale = exp(tile_m - new_m); "" if (lid < 32) { "" COMPUTE_FLOAT4 tile_out4 = (COMPUTE_FLOAT4)0; "" for (int kk = 0; kk < tile_count; ++kk) { "" const COMPUTE_FLOAT tile_weight = score_tile[kk]; "" if (tile_weight == (COMPUTE_FLOAT)0) { "" continue; "" } "" const int value_slot = k_start + kk; "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + value_slot) * 128 + out_d4; "" tile_out4 += (COMPUTE_FLOAT4)tile_weight * CONVERT_COMPUTE_FLOAT4(vload4(0, value_cache + value_offset)); "" } "" out4 = out4 * (COMPUTE_FLOAT4)old_scale + tile_out4 * (COMPUTE_FLOAT4)tile_scale; "" } "" running_l = running_l * old_scale + tile_l * tile_scale; "" running_m = new_m; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT inv_l = running_l > (COMPUTE_FLOAT)0 ? (COMPUTE_FLOAT)1 / running_l : (COMPUTE_FLOAT)0; "" const int output_offset = ((b * output_seq_len + q_index) * head_num + h) * 128; "" if (lid < 32) { "" vstore4(CONVERT_FLOAT4(out4 * (COMPUTE_FLOAT4)inv_l), 0, output + output_offset + out_d4); "" } ""}\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_READONLY_HD128(decode_causal_attention_hd128_transposed_k_readonly_row32,32)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_READONLY_HD128(decode_causal_attention_hd128_transposed_k_readonly_row64,64)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_READONLY_HD128(decode_causal_attention_hd128_transposed_k_readonly_row128,128)\n"
"#define DEFINE_DECODE_CAUSAL_TRANSPOSED_K_SPARSE_HD128(KERNEL_NAME, LANES) ""__kernel void KERNEL_NAME(GLOBAL_SIZE_3_DIMS "" __global const FLOAT *query, "" __global const FLOAT *value_cache, "" __global const FLOAT *decode_key, "" __global const int *sparse_query, "" __global FLOAT *output, "" __private const float scale, "" __private const int batch, "" __private const int query_seq_len, "" __private const int output_seq_len, "" __private const int key_seq_len, "" __private const int key_max_len, "" __private const int head_num, "" __private const int kv_head_num, "" __private const int head_dim) { "" const int x = get_global_id(0); "" const int y = get_global_id(1); "" int z = get_global_id(2); "" DEAL_NON_UNIFORM_DIM3(x, y, z); "" const int lid = get_local_id(0); "" if (get_local_size(0) != LANES || lid >= LANES || head_dim != 128) { "" return; "" } "" const int q_index = y; "" if (q_index >= output_seq_len) { "" return; "" } "" const int b = z / head_num; "" const int h = z - b * head_num; "" if (b >= batch) { "" return; "" } "" const int kvh = h / NUMHEAD_GROUP_SIZE; "" if (kvh >= kv_head_num) { "" return; "" } "" const int q_logical = sparse_query[q_index]; "" const int q_row = q_index; "" if (q_row < 0 || q_row >= query_seq_len || q_logical < 0 || q_logical >= key_seq_len || "" q_logical >= key_max_len) { "" return; "" } "" const int active_kv_seq_len = min(clamp(q_logical + 1, 0, key_seq_len), key_max_len); "" const int decode_key_base = ((b * kv_head_num + kvh) * 128) * key_max_len; "" COMPUTE_FLOAT local local_q[128]; "" COMPUTE_FLOAT local score_tile[LANES]; "" COMPUTE_FLOAT local reduce[LANES]; "" const int out_d4 = lid << 2; "" COMPUTE_FLOAT4 out4 = (COMPUTE_FLOAT4)0; "" for (int d = lid; d < 128; d += LANES) { "" const int query_offset = ((b * query_seq_len + q_row) * head_num + h) * 128 + d; "" local_q[d] = (COMPUTE_FLOAT)query[query_offset]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" COMPUTE_FLOAT running_m = (COMPUTE_FLOAT)-FLT_MAX; "" COMPUTE_FLOAT running_l = (COMPUTE_FLOAT)0; "" for (int k_start = 0; k_start < active_kv_seq_len; k_start += LANES) { "" const int tile_count = min(LANES, active_kv_seq_len - k_start); "" COMPUTE_FLOAT score = (COMPUTE_FLOAT)-FLT_MAX; "" if (lid < tile_count) { "" const int k = k_start + lid; "" score = (COMPUTE_FLOAT)0; "" for (int d4 = 0; d4 < 128; d4 += 4) { "" COMPUTE_FLOAT4 qv = (COMPUTE_FLOAT4)(local_q[d4], local_q[d4 + 1], local_q[d4 + 2], local_q[d4 + 3]); "" COMPUTE_FLOAT4 kv = (COMPUTE_FLOAT4)( "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 0) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 1) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 2) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 3) * key_max_len + k]); "" score += dot(qv, kv); "" } "" score *= (COMPUTE_FLOAT)scale; "" } "" score_tile[lid] = score; "" reduce[lid] = score; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] = fmax(reduce[lid], reduce[lid + stride]); "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_m = reduce[0]; "" COMPUTE_FLOAT tile_l_part = (COMPUTE_FLOAT)0; "" if (lid < tile_count && tile_m != (COMPUTE_FLOAT)-FLT_MAX) { "" tile_l_part = exp(score_tile[lid] - tile_m); "" } "" score_tile[lid] = tile_l_part; "" reduce[lid] = tile_l_part; "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" reduce[lid] += reduce[lid + stride]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT tile_l = reduce[0]; "" if (tile_l > (COMPUTE_FLOAT)0) { "" const COMPUTE_FLOAT new_m = running_l > (COMPUTE_FLOAT)0 ? fmax(running_m, tile_m) : tile_m; "" const COMPUTE_FLOAT old_scale = running_l > (COMPUTE_FLOAT)0 ? exp(running_m - new_m) : (COMPUTE_FLOAT)0; "" const COMPUTE_FLOAT tile_scale = exp(tile_m - new_m); "" if (lid < 32) { "" COMPUTE_FLOAT4 tile_out4 = (COMPUTE_FLOAT4)0; "" for (int kk = 0; kk < tile_count; ++kk) { "" const COMPUTE_FLOAT tile_weight = score_tile[kk]; "" if (tile_weight == (COMPUTE_FLOAT)0) { "" continue; "" } "" const int value_logical = k_start + kk; "" const int value_slot = value_logical; "" if (value_slot < 0 || value_slot >= key_max_len) { "" continue; "" } "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + value_slot) * 128 + out_d4; "" tile_out4 += (COMPUTE_FLOAT4)tile_weight * CONVERT_COMPUTE_FLOAT4(vload4(0, value_cache + value_offset)); "" } "" out4 = out4 * (COMPUTE_FLOAT4)old_scale + tile_out4 * (COMPUTE_FLOAT4)tile_scale; "" } "" running_l = running_l * old_scale + tile_l * tile_scale; "" running_m = new_m; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" const COMPUTE_FLOAT inv_l = running_l > (COMPUTE_FLOAT)0 ? (COMPUTE_FLOAT)1 / running_l : (COMPUTE_FLOAT)0; "" const int output_offset = ((b * output_seq_len + q_index) * head_num + h) * 128; "" if (lid < 32) { "" vstore4(CONVERT_FLOAT4(out4 * (COMPUTE_FLOAT4)inv_l), 0, output + output_offset + out_d4); "" } ""}\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_SPARSE_HD128(decode_causal_attention_hd128_transposed_k_sparse_row32,32)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_SPARSE_HD128(decode_causal_attention_hd128_transposed_k_sparse_row64,64)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_SPARSE_HD128(decode_causal_attention_hd128_transposed_k_sparse_row128,128)\n"
"#define DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(KERNEL_NAME, LANES, Q_TILE) ""__kernel void KERNEL_NAME(GLOBAL_SIZE_3_DIMS "" __global const FLOAT *query, "" __global const FLOAT *value_cache, "" __global const FLOAT *decode_key, """" __global const int *sparse_query, "" __global FLOAT *output, "" __private const float scale, "" __private const int batch, "" __private const int query_seq_len, "" __private const int output_seq_len, "" __private const int key_seq_len, "" __private const int key_max_len, "" __private const int head_num, "" __private const int kv_head_num, "" __private const int head_dim) { "" const int x = get_global_id(0); "" const int y = get_global_id(1); "" int z = get_global_id(2); "" DEAL_NON_UNIFORM_DIM3(x, y, z); "" const int lid = get_local_id(0); "" if (get_local_size(0) != LANES || lid >= LANES || head_dim != 128) { "" return; "" } "" const int q_base = y * Q_TILE; "" if (q_base >= output_seq_len) { "" return; "" } "" const int b = z / head_num; "" const int h = z - b * head_num; "" if (b >= batch) { "" return; "" } "" const int kvh = h / NUMHEAD_GROUP_SIZE; "" if (kvh >= kv_head_num) { "" return; "" } "" const int decode_key_base = ((b * kv_head_num + kvh) * 128) * key_max_len; "" int q_valid[Q_TILE]; "" int q_logical[Q_TILE]; "" int active_len[Q_TILE]; "" int max_active_len = 0; "" COMPUTE_FLOAT local local_q[Q_TILE * 128]; "" COMPUTE_FLOAT local score_tile[Q_TILE * LANES]; "" COMPUTE_FLOAT local reduce[Q_TILE * LANES]; "" for (int qr = 0; qr < Q_TILE; ++qr) { "" const int q_index = q_base + qr; "" q_valid[qr] = 0; "" q_logical[qr] = -1; "" active_len[qr] = 0; "" if (q_index < output_seq_len) { "" const int logical = sparse_query[q_index]; "" if (logical >= 0 && logical < key_seq_len && logical < key_max_len && q_index < query_seq_len) { "" q_valid[qr] = 1; "" q_logical[qr] = logical; "" active_len[qr] = min(clamp(logical + 1, 0, key_seq_len), key_max_len); "" max_active_len = max(max_active_len, active_len[qr]); "" } "" } "" for (int d = lid; d < 128; d += LANES) { "" COMPUTE_FLOAT qv = (COMPUTE_FLOAT)0; "" if (q_valid[qr]) { "" const int query_offset = ((b * query_seq_len + q_index) * head_num + h) * 128 + d; "" qv = (COMPUTE_FLOAT)query[query_offset]; "" } "" local_q[qr * 128 + d] = qv; "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" const int out_d4 = lid << 2; "" COMPUTE_FLOAT4 out4[Q_TILE]; "" COMPUTE_FLOAT running_m[Q_TILE]; "" COMPUTE_FLOAT running_l[Q_TILE]; "" for (int qr = 0; qr < Q_TILE; ++qr) { "" out4[qr] = (COMPUTE_FLOAT4)0; "" running_m[qr] = (COMPUTE_FLOAT)-FLT_MAX; "" running_l[qr] = (COMPUTE_FLOAT)0; "" } "" for (int k_start = 0; k_start < max_active_len; k_start += LANES) { "" const int tile_count = min(LANES, max_active_len - k_start); "" COMPUTE_FLOAT score[Q_TILE]; "" for (int qr = 0; qr < Q_TILE; ++qr) { "" score[qr] = (COMPUTE_FLOAT)-FLT_MAX; "" } "" if (lid < tile_count) { "" const int k = k_start + lid; "" for (int qr = 0; qr < Q_TILE; ++qr) { "" if (q_valid[qr] && k < active_len[qr]) { "" score[qr] = (COMPUTE_FLOAT)0; "" } "" } "" for (int d4 = 0; d4 < 128; d4 += 4) { "" COMPUTE_FLOAT4 kv = (COMPUTE_FLOAT4)( "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 0) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 1) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 2) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 3) * key_max_len + k]); "" for (int qr = 0; qr < Q_TILE; ++qr) { "" if (q_valid[qr] && k < active_len[qr]) { "" COMPUTE_FLOAT4 qv = (COMPUTE_FLOAT4)(local_q[qr * 128 + d4], "" local_q[qr * 128 + d4 + 1], "" local_q[qr * 128 + d4 + 2], "" local_q[qr * 128 + d4 + 3]); "" score[qr] += dot(qv, kv); "" } "" } "" } "" for (int qr = 0; qr < Q_TILE; ++qr) { "" if (q_valid[qr] && k < active_len[qr]) { "" score[qr] *= (COMPUTE_FLOAT)scale; "" } "" } "" } "" for (int qr = 0; qr < Q_TILE; ++qr) { "" const int base = qr * LANES; "" score_tile[base + lid] = score[qr]; "" reduce[base + lid] = score[qr]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" for (int qr = 0; qr < Q_TILE; ++qr) { "" const int base = qr * LANES; "" reduce[base + lid] = fmax(reduce[base + lid], reduce[base + lid + stride]); "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" COMPUTE_FLOAT tile_m[Q_TILE]; "" COMPUTE_FLOAT tile_l[Q_TILE]; "" for (int qr = 0; qr < Q_TILE; ++qr) { "" const int base = qr * LANES; "" tile_m[qr] = reduce[base]; "" COMPUTE_FLOAT tile_l_part = (COMPUTE_FLOAT)0; "" if (lid < tile_count && q_valid[qr] && k_start + lid < active_len[qr] && "" tile_m[qr] != (COMPUTE_FLOAT)-FLT_MAX) { "" tile_l_part = exp(score_tile[base + lid] - tile_m[qr]); "" } "" score_tile[base + lid] = tile_l_part; "" reduce[base + lid] = tile_l_part; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" for (int qr = 0; qr < Q_TILE; ++qr) { "" const int base = qr * LANES; "" reduce[base + lid] += reduce[base + lid + stride]; "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" COMPUTE_FLOAT old_scale[Q_TILE]; "" COMPUTE_FLOAT tile_scale[Q_TILE]; "" for (int qr = 0; qr < Q_TILE; ++qr) { "" tile_l[qr] = reduce[qr * LANES]; "" old_scale[qr] = (COMPUTE_FLOAT)0; "" tile_scale[qr] = (COMPUTE_FLOAT)0; "" if (q_valid[qr] && tile_l[qr] > (COMPUTE_FLOAT)0) { "" const COMPUTE_FLOAT new_m = running_l[qr] > (COMPUTE_FLOAT)0 ? fmax(running_m[qr], tile_m[qr]) : tile_m[qr]; "" old_scale[qr] = running_l[qr] > (COMPUTE_FLOAT)0 ? exp(running_m[qr] - new_m) : (COMPUTE_FLOAT)0; "" tile_scale[qr] = exp(tile_m[qr] - new_m); "" running_l[qr] = running_l[qr] * old_scale[qr] + tile_l[qr] * tile_scale[qr]; "" running_m[qr] = new_m; "" } "" } "" if (lid < 32) { "" COMPUTE_FLOAT4 tile_out4[Q_TILE]; "" for (int qr = 0; qr < Q_TILE; ++qr) { "" tile_out4[qr] = (COMPUTE_FLOAT4)0; "" } "" for (int kk = 0; kk < tile_count; ++kk) { "" const int value_logical = k_start + kk; "" const int value_slot = value_logical; "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + value_slot) * 128 + out_d4; "" const COMPUTE_FLOAT4 vv = CONVERT_COMPUTE_FLOAT4(vload4(0, value_cache + value_offset)); "" for (int qr = 0; qr < Q_TILE; ++qr) { "" const COMPUTE_FLOAT tile_weight = score_tile[qr * LANES + kk]; "" if (q_valid[qr] && value_logical < active_len[qr] && tile_weight != (COMPUTE_FLOAT)0) { "" tile_out4[qr] += (COMPUTE_FLOAT4)tile_weight * vv; "" } "" } "" } "" for (int qr = 0; qr < Q_TILE; ++qr) { "" if (q_valid[qr] && tile_l[qr] > (COMPUTE_FLOAT)0) { "" out4[qr] = out4[qr] * (COMPUTE_FLOAT4)old_scale[qr] + tile_out4[qr] * (COMPUTE_FLOAT4)tile_scale[qr]; "" } "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" if (lid < 32) { "" for (int qr = 0; qr < Q_TILE; ++qr) { "" if (q_valid[qr]) { "" const COMPUTE_FLOAT inv_l = running_l[qr] > (COMPUTE_FLOAT)0 ? (COMPUTE_FLOAT)1 / running_l[qr] : (COMPUTE_FLOAT)0; "" const int q_index = q_base + qr; "" const int output_offset = ((b * output_seq_len + q_index) * head_num + h) * 128 + out_d4; "" vstore4(CONVERT_FLOAT4(out4[qr] * (COMPUTE_FLOAT4)inv_l), 0, output + output_offset + out_d4); "" } "" } "" } ""}\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q2_row32,32,2)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q2_row64,64,2)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q2_row128,128,2)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q4_row32,32,4)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q4_row64,64,4)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q4_row128,128,4)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q8_row32,32,8)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q8_row64,64,8)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_QTILE_HD128(decode_causal_attention_hd128_transposed_k_qtile_q8_row128,128,8)\n"
"#define DEFINE_DECODE_CAUSAL_TRANSPOSED_K_FUSED_KV_GQA_HD128(KERNEL_NAME, LANES) ""__kernel void KERNEL_NAME(GLOBAL_SIZE_3_DIMS "" __global const FLOAT *query, "" __global const FLOAT *key, "" __global const FLOAT *value, "" __global FLOAT *key_cache, "" __global FLOAT *value_cache, "" __global FLOAT *decode_key, """" __global FLOAT *output, "" __private const float scale, "" __private const int batch, "" __private const int query_seq_len, "" __private const int output_seq_len, "" __private const int base_logical, "" __private const int key_seq_len, "" __private const int key_max_len, "" __private const int head_num, "" __private const int kv_head_num, "" __private const int head_dim) { "" const int x = get_global_id(0); "" const int y = get_global_id(1); "" int z = get_global_id(2); "" DEAL_NON_UNIFORM_DIM3(x, y, z); "" const int lid = get_local_id(0); "" if (get_local_size(0) != LANES || lid >= LANES || head_dim != 128 || NUMHEAD_GROUP_SIZE <= 1) { "" return; "" } "" const int q_index = y; "" if (q_index >= output_seq_len) { "" return; "" } "" const int b = z / kv_head_num; "" const int kvh = z - b * kv_head_num; "" if (b >= batch || kvh >= kv_head_num) { "" return; "" } "" const int q_logical = base_logical + q_index; "" const int q_row = q_index; "" if (q_row < 0 || q_row >= query_seq_len || q_logical < 0 || q_logical >= key_max_len) { "" return; "" } "" const int q_slot = q_logical; "" if (q_slot < 0 || q_slot >= key_max_len) { "" return; "" } "" const int decode_key_base = ((b * kv_head_num + kvh) * 128) * key_max_len; "" for (int d = lid; d < 128; d += LANES) { "" const int in_offset = ((b * output_seq_len + q_index) * kv_head_num + kvh) * 128 + d; "" const FLOAT k = key[in_offset]; "" const FLOAT v = value[in_offset]; "" key_cache[((q_slot * batch + b) * kv_head_num + kvh) * 128 + d] = k; "" value_cache[((b * kv_head_num + kvh) * key_max_len + q_slot) * 128 + d] = v; "" decode_key[decode_key_base + d * key_max_len + q_logical] = k; "" } "" barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE); "" const int active_kv_seq_len = min(clamp(q_logical + 1, 0, key_seq_len), key_max_len); "" COMPUTE_FLOAT local local_q[NUMHEAD_GROUP_SIZE * 128]; "" COMPUTE_FLOAT local score_tile[NUMHEAD_GROUP_SIZE * LANES]; "" COMPUTE_FLOAT local reduce[NUMHEAD_GROUP_SIZE * LANES]; "" const int out_d4 = lid << 2; "" COMPUTE_FLOAT4 out4[NUMHEAD_GROUP_SIZE]; "" COMPUTE_FLOAT running_m[NUMHEAD_GROUP_SIZE]; "" COMPUTE_FLOAT running_l[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" out4[gh] = (COMPUTE_FLOAT4)0; "" running_m[gh] = (COMPUTE_FLOAT)-FLT_MAX; "" running_l[gh] = (COMPUTE_FLOAT)0; "" const int h = kvh * NUMHEAD_GROUP_SIZE + gh; "" for (int d = lid; d < 128; d += LANES) { "" const int query_offset = ((b * query_seq_len + q_row) * head_num + h) * 128 + d; "" local_q[gh * 128 + d] = (COMPUTE_FLOAT)query[query_offset]; "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int k_start = 0; k_start < active_kv_seq_len; k_start += LANES) { "" const int tile_count = min(LANES, active_kv_seq_len - k_start); "" COMPUTE_FLOAT score[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" score[gh] = (COMPUTE_FLOAT)-FLT_MAX; "" } "" if (lid < tile_count) { "" const int k = k_start + lid; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" score[gh] = (COMPUTE_FLOAT)0; "" } "" for (int d4 = 0; d4 < 128; d4 += 4) { "" COMPUTE_FLOAT4 kv = (COMPUTE_FLOAT4)( "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 0) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 1) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 2) * key_max_len + k], "" (COMPUTE_FLOAT)decode_key[decode_key_base + (d4 + 3) * key_max_len + k]); "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" COMPUTE_FLOAT4 qv = (COMPUTE_FLOAT4)(local_q[gh * 128 + d4], local_q[gh * 128 + d4 + 1], "" local_q[gh * 128 + d4 + 2], local_q[gh * 128 + d4 + 3]); "" score[gh] += dot(qv, kv); "" } "" } "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" score[gh] *= (COMPUTE_FLOAT)scale; "" } "" } "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" score_tile[base + lid] = score[gh]; "" reduce[base + lid] = score[gh]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" reduce[base + lid] = fmax(reduce[base + lid], reduce[base + lid + stride]); "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" COMPUTE_FLOAT tile_m[NUMHEAD_GROUP_SIZE]; "" COMPUTE_FLOAT tile_l[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" tile_m[gh] = reduce[base]; "" COMPUTE_FLOAT tile_l_part = (COMPUTE_FLOAT)0; "" if (lid < tile_count && tile_m[gh] != (COMPUTE_FLOAT)-FLT_MAX) { "" tile_l_part = exp(score_tile[base + lid] - tile_m[gh]); "" } "" score_tile[base + lid] = tile_l_part; "" reduce[base + lid] = tile_l_part; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" reduce[base + lid] += reduce[base + lid + stride]; "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" COMPUTE_FLOAT old_scale[NUMHEAD_GROUP_SIZE]; "" COMPUTE_FLOAT tile_scale[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" tile_l[gh] = reduce[base]; "" old_scale[gh] = (COMPUTE_FLOAT)0; "" tile_scale[gh] = (COMPUTE_FLOAT)0; "" if (tile_l[gh] > (COMPUTE_FLOAT)0) { "" const COMPUTE_FLOAT new_m = running_l[gh] > (COMPUTE_FLOAT)0 ? fmax(running_m[gh], tile_m[gh]) : tile_m[gh]; "" old_scale[gh] = running_l[gh] > (COMPUTE_FLOAT)0 ? exp(running_m[gh] - new_m) : (COMPUTE_FLOAT)0; "" tile_scale[gh] = exp(tile_m[gh] - new_m); "" running_l[gh] = running_l[gh] * old_scale[gh] + tile_l[gh] * tile_scale[gh]; "" running_m[gh] = new_m; "" } "" } "" if (lid < 32) { "" COMPUTE_FLOAT4 tile_out4[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" tile_out4[gh] = (COMPUTE_FLOAT4)0; "" } "" for (int kk = 0; kk < tile_count; ++kk) { "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + (k_start + kk)) * 128 + out_d4; "" COMPUTE_FLOAT4 vv = CONVERT_COMPUTE_FLOAT4(vload4(0, value_cache + value_offset)); "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const COMPUTE_FLOAT tile_weight = score_tile[gh * LANES + kk]; "" if (tile_weight != (COMPUTE_FLOAT)0) { "" tile_out4[gh] += (COMPUTE_FLOAT4)tile_weight * vv; "" } "" } "" } "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" if (tile_l[gh] > (COMPUTE_FLOAT)0) { "" out4[gh] = out4[gh] * (COMPUTE_FLOAT4)old_scale[gh] + tile_out4[gh] * (COMPUTE_FLOAT4)tile_scale[gh]; "" } "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" if (lid < 32) { "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const COMPUTE_FLOAT inv_l = running_l[gh] > (COMPUTE_FLOAT)0 ? (COMPUTE_FLOAT)1 / running_l[gh] : (COMPUTE_FLOAT)0; "" const int h = kvh * NUMHEAD_GROUP_SIZE + gh; "" const int output_offset = ((b * output_seq_len + q_index) * head_num + h) * 128; "" vstore4(CONVERT_FLOAT4(out4[gh] * (COMPUTE_FLOAT4)inv_l), 0, output + output_offset + out_d4); "" } "" } ""}\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_FUSED_KV_GQA_HD128(decode_causal_attention_hd128_transposed_k_fused_kv_gqa_row32,32)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_FUSED_KV_GQA_HD128(decode_causal_attention_hd128_transposed_k_fused_kv_gqa_row64,64)\n"
"DEFINE_DECODE_CAUSAL_TRANSPOSED_K_FUSED_KV_GQA_HD128(decode_causal_attention_hd128_transposed_k_fused_kv_gqa_row128,128)\n"
"#define DEFINE_DECODE_CAUSAL_IDENTITY_FUSED_KV_GQA_HD128(KERNEL_NAME, LANES) ""__kernel void KERNEL_NAME(GLOBAL_SIZE_3_DIMS "" __global const FLOAT *query, "" __global const FLOAT *key, "" __global const FLOAT *value, "" __global FLOAT *key_cache, "" __global FLOAT *value_cache, "" __global FLOAT *output, "" __private const float scale, "" __private const int batch, "" __private const int query_seq_len, "" __private const int output_seq_len, "" __private const int base_logical, "" __private const int key_seq_len, "" __private const int key_max_len, "" __private const int head_num, "" __private const int kv_head_num, "" __private const int head_dim) { "" const int x = get_global_id(0); "" const int y = get_global_id(1); "" int z = get_global_id(2); "" DEAL_NON_UNIFORM_DIM3(x, y, z); "" const int lid = get_local_id(0); "" if (get_local_size(0) != LANES || lid >= LANES || head_dim != 128 || NUMHEAD_GROUP_SIZE <= 1) { "" return; "" } "" const int q_index = y; "" if (q_index >= output_seq_len) { "" return; "" } "" const int b = z / kv_head_num; "" const int kvh = z - b * kv_head_num; "" if (b >= batch || kvh >= kv_head_num) { "" return; "" } "" const int q_logical = base_logical + q_index; "" const int q_row = q_index; "" if (q_row < 0 || q_row >= query_seq_len || q_logical < 0 || q_logical >= key_max_len) { "" return; "" } "" for (int d = lid; d < 128; d += LANES) { "" const int in_offset = ((b * output_seq_len + q_index) * kv_head_num + kvh) * 128 + d; "" const int key_offset = ((q_logical * batch + b) * kv_head_num + kvh) * 128 + d; "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + q_logical) * 128 + d; "" key_cache[key_offset] = key[in_offset]; "" value_cache[value_offset] = value[in_offset]; "" } "" barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE); "" const int active_kv_seq_len = min(clamp(q_logical + 1, 0, key_seq_len), key_max_len); "" COMPUTE_FLOAT local local_q[NUMHEAD_GROUP_SIZE * 128]; "" COMPUTE_FLOAT local score_tile[NUMHEAD_GROUP_SIZE * LANES]; "" COMPUTE_FLOAT local reduce[NUMHEAD_GROUP_SIZE * LANES]; "" const int out_d4 = lid << 2; "" COMPUTE_FLOAT4 out4[NUMHEAD_GROUP_SIZE]; "" COMPUTE_FLOAT running_m[NUMHEAD_GROUP_SIZE]; "" COMPUTE_FLOAT running_l[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" out4[gh] = (COMPUTE_FLOAT4)0; "" running_m[gh] = (COMPUTE_FLOAT)-FLT_MAX; "" running_l[gh] = (COMPUTE_FLOAT)0; "" const int h = kvh * NUMHEAD_GROUP_SIZE + gh; "" for (int d = lid; d < 128; d += LANES) { "" const int query_offset = ((b * query_seq_len + q_row) * head_num + h) * 128 + d; "" local_q[gh * 128 + d] = (COMPUTE_FLOAT)query[query_offset]; "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int k_start = 0; k_start < active_kv_seq_len; k_start += LANES) { "" const int tile_count = min(LANES, active_kv_seq_len - k_start); "" COMPUTE_FLOAT score[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" score[gh] = (COMPUTE_FLOAT)-FLT_MAX; "" } "" if (lid < tile_count) { "" const int k = k_start + lid; "" const int key_offset = ((k * batch + b) * kv_head_num + kvh) * 128; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" score[gh] = (COMPUTE_FLOAT)0; "" } "" for (int d4 = 0; d4 < 128; d4 += 4) { "" COMPUTE_FLOAT4 kv = CONVERT_COMPUTE_FLOAT4(vload4(0, key_cache + key_offset + d4)); "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" COMPUTE_FLOAT4 qv = (COMPUTE_FLOAT4)(local_q[gh * 128 + d4], local_q[gh * 128 + d4 + 1], "" local_q[gh * 128 + d4 + 2], local_q[gh * 128 + d4 + 3]); "" score[gh] += dot(qv, kv); "" } "" } "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" score[gh] *= (COMPUTE_FLOAT)scale; "" } "" } "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" score_tile[base + lid] = score[gh]; "" reduce[base + lid] = score[gh]; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" reduce[base + lid] = fmax(reduce[base + lid], reduce[base + lid + stride]); "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" COMPUTE_FLOAT tile_m[NUMHEAD_GROUP_SIZE]; "" COMPUTE_FLOAT tile_l[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" tile_m[gh] = reduce[base]; "" COMPUTE_FLOAT tile_l_part = (COMPUTE_FLOAT)0; "" if (lid < tile_count && tile_m[gh] != (COMPUTE_FLOAT)-FLT_MAX) { "" tile_l_part = exp(score_tile[base + lid] - tile_m[gh]); "" } "" score_tile[base + lid] = tile_l_part; "" reduce[base + lid] = tile_l_part; "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" for (int stride = LANES >> 1; stride > 0; stride >>= 1) { "" if (lid < stride) { "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" reduce[base + lid] += reduce[base + lid + stride]; "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" COMPUTE_FLOAT old_scale[NUMHEAD_GROUP_SIZE]; "" COMPUTE_FLOAT tile_scale[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const int base = gh * LANES; "" tile_l[gh] = reduce[base]; "" old_scale[gh] = (COMPUTE_FLOAT)0; "" tile_scale[gh] = (COMPUTE_FLOAT)0; "" if (tile_l[gh] > (COMPUTE_FLOAT)0) { "" const COMPUTE_FLOAT new_m = running_l[gh] > (COMPUTE_FLOAT)0 ? fmax(running_m[gh], tile_m[gh]) : tile_m[gh]; "" old_scale[gh] = running_l[gh] > (COMPUTE_FLOAT)0 ? exp(running_m[gh] - new_m) : (COMPUTE_FLOAT)0; "" tile_scale[gh] = exp(tile_m[gh] - new_m); "" running_l[gh] = running_l[gh] * old_scale[gh] + tile_l[gh] * tile_scale[gh]; "" running_m[gh] = new_m; "" } "" } "" if (lid < 32) { "" COMPUTE_FLOAT4 tile_out4[NUMHEAD_GROUP_SIZE]; "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" tile_out4[gh] = (COMPUTE_FLOAT4)0; "" } "" for (int kk = 0; kk < tile_count; ++kk) { "" const int value_offset = ((b * kv_head_num + kvh) * key_max_len + (k_start + kk)) * 128 + out_d4; "" COMPUTE_FLOAT4 vv = CONVERT_COMPUTE_FLOAT4(vload4(0, value_cache + value_offset)); "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const COMPUTE_FLOAT tile_weight = score_tile[gh * LANES + kk]; "" if (tile_weight != (COMPUTE_FLOAT)0) { "" tile_out4[gh] += (COMPUTE_FLOAT4)tile_weight * vv; "" } "" } "" } "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" if (tile_l[gh] > (COMPUTE_FLOAT)0) { "" out4[gh] = out4[gh] * (COMPUTE_FLOAT4)old_scale[gh] + tile_out4[gh] * (COMPUTE_FLOAT4)tile_scale[gh]; "" } "" } "" } "" barrier(CLK_LOCAL_MEM_FENCE); "" } "" if (lid < 32) { "" for (int gh = 0; gh < NUMHEAD_GROUP_SIZE; ++gh) { "" const COMPUTE_FLOAT inv_l = running_l[gh] > (COMPUTE_FLOAT)0 ? (COMPUTE_FLOAT)1 / running_l[gh] : (COMPUTE_FLOAT)0; "" const int h = kvh * NUMHEAD_GROUP_SIZE + gh; "" const int output_offset = ((b * output_seq_len + q_index) * head_num + h) * 128; "" vstore4(CONVERT_FLOAT4(out4[gh] * (COMPUTE_FLOAT4)inv_l), 0, output + output_offset + out_d4); "" } "" } ""}\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_FUSED_KV_GQA_HD128(decode_causal_attention_hd128_identity_fused_kv_gqa_row32,32)\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_FUSED_KV_GQA_HD128(decode_causal_attention_hd128_identity_fused_kv_gqa_row64,64)\n"
"DEFINE_DECODE_CAUSAL_IDENTITY_FUSED_KV_GQA_HD128(decode_causal_attention_hd128_identity_fused_kv_gqa_row128,128)\n"
;
#endif
}
