#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* paged_attention_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"__kernel void zero_output(\n"
" __global FLOAT* output,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" output[index]=(FLOAT)0;\n"
"}\n"
"__kernel void copy_paged_kv(\n"
" __global const FLOAT* key,\n"
" __global const FLOAT* value,\n"
" __global FLOAT* key_cache,\n"
" __global FLOAT* value_cache,\n"
" __global const int* slot_table,\n"
" __global const int* sparse_query,\n"
" const int batch,\n"
" const int new_kv_len,\n"
" const int kv_write_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int base_logical,\n"
" const int max_slots,\n"
" const int sparse_active,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int d=index % head_dim;\n"
" int t=index/head_dim;\n"
" int h=t % kv_heads;\n"
" t=t/kv_heads;\n"
" int l=t % kv_write_len;\n"
" int b=t/kv_write_len;\n"
" int logical=sparse_active ? sparse_query[l] : (base_logical+l);\n"
" if (logical<0) {\n"
" return;\n"
" }\n"
" int slot=slot_table[logical];\n"
" if (slot<0 || slot >= max_slots || l >= new_kv_len) {\n"
" return;\n"
" }\n"
" int in_offset=((b*new_kv_len+l)*kv_heads+h)*head_dim+d;\n"
" int k_offset=((slot*batch+b)*kv_heads+h)*head_dim+d;\n"
" int v_offset=((b*kv_heads+h)*max_slots+slot)*head_dim+d;\n"
" key_cache[k_offset]=key[in_offset];\n"
" value_cache[v_offset]=value[in_offset];\n"
"}\n"
"__kernel void pack_paged_kv_prefill(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global const FLOAT* value_cache,// [batch,kv_heads,max_slots,head_dim]\n"
" __global FLOAT* packed_key,// [batch*kv_heads,head_dim_pack,kv_len_pack]\n"
" __global FLOAT* packed_value,// [batch*kv_heads,kv_len_pack,head_dim_pack]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots) {\n"
" const int x=get_global_id(0); // kv token/4\n"
" const int y=get_global_id(1); // head dim/4\n"
" int z=get_global_id(2); // batch*kv_heads\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int logical4=x << 2;\n"
" const int dim4=y << 2;\n"
" const int head_dim_pack=((head_dim+3)/4)*4;\n"
" const int kv_len_pack=((kv_len+3)/4)*4;\n"
" const int b=z/kv_heads;\n"
" const int h=z-b*kv_heads;\n"
" FLOAT4 k0=(FLOAT4)0;\n"
" FLOAT4 k1=(FLOAT4)0;\n"
" FLOAT4 k2=(FLOAT4)0;\n"
" FLOAT4 k3=(FLOAT4)0;\n"
" FLOAT4 v0=(FLOAT4)0;\n"
" FLOAT4 v1=(FLOAT4)0;\n"
" FLOAT4 v2=(FLOAT4)0;\n"
" FLOAT4 v3=(FLOAT4)0;\n"
" if (dim4<head_dim) {\n"
" int slot0=logical4<kv_len ? slot_table[logical4] : -1;\n"
" int slot1=logical4+1<kv_len ? slot_table[logical4+1] : -1;\n"
" int slot2=logical4+2<kv_len ? slot_table[logical4+2] : -1;\n"
" int slot3=logical4+3<kv_len ? slot_table[logical4+3] : -1;\n"
" if (slot0 >= 0 && slot0<max_slots) {\n"
" k0=vload4(0,key_cache+((slot0*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v0=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot0)*head_dim+dim4);\n"
" }\n"
" if (slot1 >= 0 && slot1<max_slots) {\n"
" k1=vload4(0,key_cache+((slot1*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v1=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot1)*head_dim+dim4);\n"
" }\n"
" if (slot2 >= 0 && slot2<max_slots) {\n"
" k2=vload4(0,key_cache+((slot2*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v2=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot2)*head_dim+dim4);\n"
" }\n"
" if (slot3 >= 0 && slot3<max_slots) {\n"
" k3=vload4(0,key_cache+((slot3*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v3=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot3)*head_dim+dim4);\n"
" }\n"
" if (dim4+3 >= head_dim) {\n"
" if (dim4+1 >= head_dim) {\n"
" k0.yzw=(FLOAT3)0; k1.yzw=(FLOAT3)0; k2.yzw=(FLOAT3)0; k3.yzw=(FLOAT3)0;\n"
" v0.yzw=(FLOAT3)0; v1.yzw=(FLOAT3)0; v2.yzw=(FLOAT3)0; v3.yzw=(FLOAT3)0;\n"
" } else if (dim4+2 >= head_dim) {\n"
" k0.zw=(FLOAT2)0; k1.zw=(FLOAT2)0; k2.zw=(FLOAT2)0; k3.zw=(FLOAT2)0;\n"
" v0.zw=(FLOAT2)0; v1.zw=(FLOAT2)0; v2.zw=(FLOAT2)0; v3.zw=(FLOAT2)0;\n"
" } else {\n"
" k0.w=(FLOAT)0; k1.w=(FLOAT)0; k2.w=(FLOAT)0; k3.w=(FLOAT)0;\n"
" v0.w=(FLOAT)0; v1.w=(FLOAT)0; v2.w=(FLOAT)0; v3.w=(FLOAT)0;\n"
" }\n"
" }\n"
" }\n"
" const int key_offset=(z*head_dim_pack+dim4)*kv_len_pack+logical4;\n"
" vstore4((FLOAT4)(k0.s0,k1.s0,k2.s0,k3.s0),0,packed_key+key_offset);\n"
" vstore4((FLOAT4)(k0.s1,k1.s1,k2.s1,k3.s1),0,packed_key+key_offset+kv_len_pack);\n"
" vstore4((FLOAT4)(k0.s2,k1.s2,k2.s2,k3.s2),0,packed_key+key_offset+kv_len_pack*2);\n"
" vstore4((FLOAT4)(k0.s3,k1.s3,k2.s3,k3.s3),0,packed_key+key_offset+kv_len_pack*3);\n"
" const int value_offset=(z*kv_len_pack+logical4)*head_dim_pack+dim4;\n"
" vstore4(v0,0,packed_value+value_offset);\n"
" vstore4(v1,0,packed_value+value_offset+head_dim_pack);\n"
" vstore4(v2,0,packed_value+value_offset+head_dim_pack*2);\n"
" vstore4(v3,0,packed_value+value_offset+head_dim_pack*3);\n"
"}\n"
"__kernel void rearrange_paged_q_gemm_prefill(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT* query,// [batch,query_seq_len,head_num,head_dim]\n"
" __global FLOAT* packed_query,// [batch*head_num,head_dim_pack,query_seq_len_pack]\n"
" const int seq_len,\n"
" const int head_dim,\n"
" const int head_num,\n"
" const int seq_len_pack) {\n"
" const int x=get_global_id(0); // query token/4\n"
" const int y=get_global_id(1); // head dim/4\n"
" int z=get_global_id(2); // batch*head_num\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int x4=x << 2;\n"
" const int y4=y << 2;\n"
" const int b=z/head_num;\n"
" const int h=z-b*head_num;\n"
" FLOAT4 q0=(FLOAT4)0;\n"
" FLOAT4 q1=(FLOAT4)0;\n"
" FLOAT4 q2=(FLOAT4)0;\n"
" FLOAT4 q3=(FLOAT4)0;\n"
" if (x4<seq_len && y4<head_dim) {\n"
" const int stride=head_num*head_dim;\n"
" int query_offset=((b*seq_len+x4)*head_num+h)*head_dim+y4;\n"
" q0=vload4(0,query+query_offset);\n"
" q1=x4+1<seq_len ? vload4(0,query+query_offset+stride) : (FLOAT4)0;\n"
" q2=x4+2<seq_len ? vload4(0,query+query_offset+stride*2) : (FLOAT4)0;\n"
" q3=x4+3<seq_len ? vload4(0,query+query_offset+stride*3) : (FLOAT4)0;\n"
" if (y4+3 >= head_dim) {\n"
" if (y4+1 >= head_dim) {\n"
" q0.yzw=(FLOAT3)0; q1.yzw=(FLOAT3)0; q2.yzw=(FLOAT3)0; q3.yzw=(FLOAT3)0;\n"
" } else if (y4+2 >= head_dim) {\n"
" q0.zw=(FLOAT2)0; q1.zw=(FLOAT2)0; q2.zw=(FLOAT2)0; q3.zw=(FLOAT2)0;\n"
" } else {\n"
" q0.w=(FLOAT)0; q1.w=(FLOAT)0; q2.w=(FLOAT)0; q3.w=(FLOAT)0;\n"
" }\n"
" }\n"
" }\n"
" const int out_offset=((z*head_dim+y4)*seq_len_pack+x4);\n"
" vstore4((FLOAT4)(q0.s0,q1.s0,q2.s0,q3.s0),0,packed_query+out_offset);\n"
" vstore4((FLOAT4)(q0.s1,q1.s1,q2.s1,q3.s1),0,packed_query+out_offset+seq_len_pack);\n"
" vstore4((FLOAT4)(q0.s2,q1.s2,q2.s2,q3.s2),0,packed_query+out_offset+seq_len_pack*2);\n"
" vstore4((FLOAT4)(q0.s3,q1.s3,q2.s3,q3.s3),0,packed_query+out_offset+seq_len_pack*3);\n"
"}\n"
"__kernel void pack_paged_kv_prefill_gemm(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global const FLOAT* value_cache,// [batch,kv_heads,max_slots,head_dim]\n"
" __global FLOAT* packed_key,// [batch*kv_heads,head_dim_pack,kv_len_pack]\n"
" __global FLOAT* packed_value,// [batch*kv_heads,kv_len_pack,head_dim_pack]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int kv_len_pack,\n"
" const int head_dim_pack) {\n"
" const int x=get_global_id(0); // kv token/4\n"
" const int y=get_global_id(1); // head dim/4\n"
" int z=get_global_id(2); // batch*kv_heads\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int logical4=x << 2;\n"
" const int dim4=y << 2;\n"
" const int b=z/kv_heads;\n"
" const int h=z-b*kv_heads;\n"
" FLOAT4 k0=(FLOAT4)0;\n"
" FLOAT4 k1=(FLOAT4)0;\n"
" FLOAT4 k2=(FLOAT4)0;\n"
" FLOAT4 k3=(FLOAT4)0;\n"
" FLOAT4 v0=(FLOAT4)0;\n"
" FLOAT4 v1=(FLOAT4)0;\n"
" FLOAT4 v2=(FLOAT4)0;\n"
" FLOAT4 v3=(FLOAT4)0;\n"
" if (dim4<head_dim) {\n"
" int slot0=logical4<kv_len ? slot_table[logical4] : -1;\n"
" int slot1=logical4+1<kv_len ? slot_table[logical4+1] : -1;\n"
" int slot2=logical4+2<kv_len ? slot_table[logical4+2] : -1;\n"
" int slot3=logical4+3<kv_len ? slot_table[logical4+3] : -1;\n"
" if (slot0 >= 0 && slot0<max_slots) {\n"
" k0=vload4(0,key_cache+((slot0*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v0=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot0)*head_dim+dim4);\n"
" }\n"
" if (slot1 >= 0 && slot1<max_slots) {\n"
" k1=vload4(0,key_cache+((slot1*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v1=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot1)*head_dim+dim4);\n"
" }\n"
" if (slot2 >= 0 && slot2<max_slots) {\n"
" k2=vload4(0,key_cache+((slot2*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v2=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot2)*head_dim+dim4);\n"
" }\n"
" if (slot3 >= 0 && slot3<max_slots) {\n"
" k3=vload4(0,key_cache+((slot3*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v3=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot3)*head_dim+dim4);\n"
" }\n"
" if (dim4+3 >= head_dim) {\n"
" if (dim4+1 >= head_dim) {\n"
" k0.yzw=(FLOAT3)0; k1.yzw=(FLOAT3)0; k2.yzw=(FLOAT3)0; k3.yzw=(FLOAT3)0;\n"
" v0.yzw=(FLOAT3)0; v1.yzw=(FLOAT3)0; v2.yzw=(FLOAT3)0; v3.yzw=(FLOAT3)0;\n"
" } else if (dim4+2 >= head_dim) {\n"
" k0.zw=(FLOAT2)0; k1.zw=(FLOAT2)0; k2.zw=(FLOAT2)0; k3.zw=(FLOAT2)0;\n"
" v0.zw=(FLOAT2)0; v1.zw=(FLOAT2)0; v2.zw=(FLOAT2)0; v3.zw=(FLOAT2)0;\n"
" } else {\n"
" k0.w=(FLOAT)0; k1.w=(FLOAT)0; k2.w=(FLOAT)0; k3.w=(FLOAT)0;\n"
" v0.w=(FLOAT)0; v1.w=(FLOAT)0; v2.w=(FLOAT)0; v3.w=(FLOAT)0;\n"
" }\n"
" }\n"
" }\n"
" const int key_offset=(z*head_dim_pack+dim4)*kv_len_pack+logical4;\n"
" vstore4((FLOAT4)(k0.s0,k1.s0,k2.s0,k3.s0),0,packed_key+key_offset);\n"
" vstore4((FLOAT4)(k0.s1,k1.s1,k2.s1,k3.s1),0,packed_key+key_offset+kv_len_pack);\n"
" vstore4((FLOAT4)(k0.s2,k1.s2,k2.s2,k3.s2),0,packed_key+key_offset+kv_len_pack*2);\n"
" vstore4((FLOAT4)(k0.s3,k1.s3,k2.s3,k3.s3),0,packed_key+key_offset+kv_len_pack*3);\n"
" const int value_offset=(z*kv_len_pack+logical4)*head_dim_pack+dim4;\n"
" vstore4(v0,0,packed_value+value_offset);\n"
" vstore4(v1,0,packed_value+value_offset+head_dim_pack);\n"
" vstore4(v2,0,packed_value+value_offset+head_dim_pack*2);\n"
" vstore4(v3,0,packed_value+value_offset+head_dim_pack*3);\n"
"}\n"
"__kernel void pack_paged_k_prefill(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global FLOAT* packed_key,// [batch*kv_heads,head_dim_pack,kv_len_pack]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots) {\n"
" const int x=get_global_id(0); // kv token/4\n"
" const int y=get_global_id(1); // head dim/4\n"
" int z=get_global_id(2); // batch*kv_heads\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int logical4=x << 2;\n"
" const int dim4=y << 2;\n"
" const int head_dim_pack=((head_dim+3)/4)*4;\n"
" const int kv_len_pack=((kv_len+3)/4)*4;\n"
" const int b=z/kv_heads;\n"
" const int h=z-b*kv_heads;\n"
" FLOAT4 k0=(FLOAT4)0;\n"
" FLOAT4 k1=(FLOAT4)0;\n"
" FLOAT4 k2=(FLOAT4)0;\n"
" FLOAT4 k3=(FLOAT4)0;\n"
" if (dim4<head_dim) {\n"
" int slot0=logical4<kv_len ? slot_table[logical4] : -1;\n"
" int slot1=logical4+1<kv_len ? slot_table[logical4+1] : -1;\n"
" int slot2=logical4+2<kv_len ? slot_table[logical4+2] : -1;\n"
" int slot3=logical4+3<kv_len ? slot_table[logical4+3] : -1;\n"
" if (slot0 >= 0 && slot0<max_slots) {\n"
" k0=vload4(0,key_cache+((slot0*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot1 >= 0 && slot1<max_slots) {\n"
" k1=vload4(0,key_cache+((slot1*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot2 >= 0 && slot2<max_slots) {\n"
" k2=vload4(0,key_cache+((slot2*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot3 >= 0 && slot3<max_slots) {\n"
" k3=vload4(0,key_cache+((slot3*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (dim4+3 >= head_dim) {\n"
" if (dim4+1 >= head_dim) {\n"
" k0.yzw=(FLOAT3)0; k1.yzw=(FLOAT3)0; k2.yzw=(FLOAT3)0; k3.yzw=(FLOAT3)0;\n"
" } else if (dim4+2 >= head_dim) {\n"
" k0.zw=(FLOAT2)0; k1.zw=(FLOAT2)0; k2.zw=(FLOAT2)0; k3.zw=(FLOAT2)0;\n"
" } else {\n"
" k0.w=(FLOAT)0; k1.w=(FLOAT)0; k2.w=(FLOAT)0; k3.w=(FLOAT)0;\n"
" }\n"
" }\n"
" }\n"
" const int key_offset=(z*head_dim_pack+dim4)*kv_len_pack+logical4;\n"
" vstore4((FLOAT4)(k0.s0,k1.s0,k2.s0,k3.s0),0,packed_key+key_offset);\n"
" vstore4((FLOAT4)(k0.s1,k1.s1,k2.s1,k3.s1),0,packed_key+key_offset+kv_len_pack);\n"
" vstore4((FLOAT4)(k0.s2,k1.s2,k2.s2,k3.s2),0,packed_key+key_offset+kv_len_pack*2);\n"
" vstore4((FLOAT4)(k0.s3,k1.s3,k2.s3,k3.s3),0,packed_key+key_offset+kv_len_pack*3);\n"
"}\n"
"__kernel void pack_paged_k_prefill_to_image(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __write_only image2d_t packed_key,// linearized [batch*kv_heads,head_dim_pack,kv_len_pack]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int image_width) {\n"
" const int x=get_global_id(0); // kv token/4\n"
" const int y=get_global_id(1); // head dim/4\n"
" int z=get_global_id(2); // batch*kv_heads\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int logical4=x << 2;\n"
" const int dim4=y << 2;\n"
" const int head_dim_pack=((head_dim+3)/4)*4;\n"
" const int kv_len_pack=((kv_len+3)/4)*4;\n"
" const int b=z/kv_heads;\n"
" const int h=z-b*kv_heads;\n"
" FLOAT4 k0=(FLOAT4)0;\n"
" FLOAT4 k1=(FLOAT4)0;\n"
" FLOAT4 k2=(FLOAT4)0;\n"
" FLOAT4 k3=(FLOAT4)0;\n"
" if (dim4<head_dim) {\n"
" int slot0=logical4<kv_len ? slot_table[logical4] : -1;\n"
" int slot1=logical4+1<kv_len ? slot_table[logical4+1] : -1;\n"
" int slot2=logical4+2<kv_len ? slot_table[logical4+2] : -1;\n"
" int slot3=logical4+3<kv_len ? slot_table[logical4+3] : -1;\n"
" if (slot0 >= 0 && slot0<max_slots) {\n"
" k0=vload4(0,key_cache+((slot0*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot1 >= 0 && slot1<max_slots) {\n"
" k1=vload4(0,key_cache+((slot1*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot2 >= 0 && slot2<max_slots) {\n"
" k2=vload4(0,key_cache+((slot2*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot3 >= 0 && slot3<max_slots) {\n"
" k3=vload4(0,key_cache+((slot3*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (dim4+3 >= head_dim) {\n"
" if (dim4+1 >= head_dim) {\n"
" k0.yzw=(FLOAT3)0; k1.yzw=(FLOAT3)0; k2.yzw=(FLOAT3)0; k3.yzw=(FLOAT3)0;\n"
" } else if (dim4+2 >= head_dim) {\n"
" k0.zw=(FLOAT2)0; k1.zw=(FLOAT2)0; k2.zw=(FLOAT2)0; k3.zw=(FLOAT2)0;\n"
" } else {\n"
" k0.w=(FLOAT)0; k1.w=(FLOAT)0; k2.w=(FLOAT)0; k3.w=(FLOAT)0;\n"
" }\n"
" }\n"
" }\n"
" const int key_offset=(z*head_dim_pack+dim4)*kv_len_pack+logical4;\n"
" const int pixel0=key_offset >> 2;\n"
" const int pixel1=(key_offset+kv_len_pack) >> 2;\n"
" const int pixel2=(key_offset+kv_len_pack*2) >> 2;\n"
" const int pixel3=(key_offset+kv_len_pack*3) >> 2;\n"
" WI_F(packed_key,(int2)(pixel0-(pixel0/image_width)*image_width,pixel0/image_width),\n"
" (FLOAT4)(k0.s0,k1.s0,k2.s0,k3.s0));\n"
" WI_F(packed_key,(int2)(pixel1-(pixel1/image_width)*image_width,pixel1/image_width),\n"
" (FLOAT4)(k0.s1,k1.s1,k2.s1,k3.s1));\n"
" WI_F(packed_key,(int2)(pixel2-(pixel2/image_width)*image_width,pixel2/image_width),\n"
" (FLOAT4)(k0.s2,k1.s2,k2.s2,k3.s2));\n"
" WI_F(packed_key,(int2)(pixel3-(pixel3/image_width)*image_width,pixel3/image_width),\n"
" (FLOAT4)(k0.s3,k1.s3,k2.s3,k3.s3));\n"
"}\n"
"static inline float paged_rope_inv_freq(\n"
" const float theta,\n"
" const int rope_type_llama3,\n"
" const float factor,\n"
" const float low_freq_factor,\n"
" const float high_freq_factor,\n"
" const int old_context,\n"
" const int pair_index,\n"
" const int rope_dim) {\n"
" float inv_freq=pow(theta,-((float)(2*pair_index))/(float)rope_dim);\n"
" if (rope_type_llama3 == 0 || old_context <= 0 || factor == 1.0f || low_freq_factor == high_freq_factor) {\n"
" return inv_freq;\n"
" }\n"
" const float two_pi=6.28318530717958647692f;\n"
" const float wavelen=two_pi/inv_freq;\n"
" const float low_freq_wavelen=(float)old_context/low_freq_factor;\n"
" const float high_freq_wavelen=(float)old_context/high_freq_factor;\n"
" float scaled=wavelen>low_freq_wavelen ? inv_freq/factor : inv_freq;\n"
" if (wavelen >= high_freq_wavelen && wavelen <= low_freq_wavelen) {\n"
" const float smooth=((float)old_context/wavelen-low_freq_factor)/(high_freq_factor-low_freq_factor);\n"
" scaled=(1.0f-smooth)*inv_freq/factor+smooth*inv_freq;\n"
" }\n"
" return scaled;\n"
"}\n"
"__kernel void pic_page_attention_hydrate_kv(\n"
" __global const FLOAT* source_key,// [token_count,batch,kv_heads,head_dim]\n"
" __global const FLOAT* source_value,// [batch,kv_heads,token_count,head_dim]\n"
" __global FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global FLOAT* value_cache,// [batch,kv_heads,max_slots,head_dim]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int logical_start,\n"
" const int token_count,\n"
" const int key_source_logical_start,\n"
" const int value_source_start,\n"
" const int value_source_stride,\n"
" const int hydrate_value,\n"
" const int rope_dim_in,\n"
" const float rope_theta,\n"
" const int rope_type_llama3,\n"
" const float rope_scaling_factor,\n"
" const float rope_scaling_low_freq_factor,\n"
" const float rope_scaling_high_freq_factor,\n"
" const int rope_scaling_original_max_position_embeddings,\n"
" const int max_position_embeddings,\n"
" const float rope_attention_scaling,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int d=index % head_dim;\n"
" int t=index/head_dim;\n"
" int h=t % kv_heads;\n"
" t=t/kv_heads;\n"
" int b=t % batch;\n"
" int local_index=t/batch;\n"
" if (local_index >= token_count) {\n"
" return;\n"
" }\n"
" int logical=logical_start+local_index;\n"
" int slot=slot_table[logical];\n"
" if (slot<0 || slot >= max_slots) {\n"
" return;\n"
" }\n"
" int source_token=key_source_logical_start+local_index;\n"
" if (source_token<0 || source_token >= token_count) {\n"
" if (key_source_logical_start <= 0) {\n"
" return;\n"
" }\n"
" if (source_token >= max_slots) {\n"
" return;\n"
" }\n"
" }\n"
" int value_source_token=value_source_start+local_index;\n"
" if (value_source_token<0 || value_source_token >= value_source_stride) {\n"
" return;\n"
" }\n"
" int key_src_base=((source_token*batch+b)*kv_heads+h)*head_dim;\n"
" int key_dst_base=((slot*batch+b)*kv_heads+h)*head_dim;\n"
" int value_src=((b*kv_heads+h)*value_source_stride+value_source_token)*head_dim+d;\n"
" int value_dst=((b*kv_heads+h)*max_slots+slot)*head_dim+d;\n"
" int rope_dim=min(rope_dim_in>0 ? rope_dim_in : head_dim,head_dim);\n"
" rope_dim=(rope_dim/2)*2;\n"
" int rope_half=rope_dim/2;\n"
" if (d<rope_half) {\n"
" int pair=d;\n"
" float inv_freq=paged_rope_inv_freq(\n"
" rope_theta>0.0f ? rope_theta : 10000.0f,\n"
" rope_type_llama3,\n"
" max(rope_scaling_factor,1.0f),\n"
" max(rope_scaling_low_freq_factor,1.0e-6f),\n"
" max(rope_scaling_high_freq_factor,1.0e-6f),\n"
" rope_scaling_original_max_position_embeddings>0 ? rope_scaling_original_max_position_embeddings\n"
" : max_position_embeddings,\n"
" pair,\n"
" rope_dim);\n"
" float angle=(float)logical*inv_freq;\n"
" float c=cos(angle);\n"
" float s=sin(angle);\n"
" float x0=(float)source_key[key_src_base+pair];\n"
" float x1=(float)source_key[key_src_base+pair+rope_half];\n"
" key_cache[key_dst_base+pair]=(FLOAT)((x0*c-x1*s)*rope_attention_scaling);\n"
" key_cache[key_dst_base+pair+rope_half]=(FLOAT)((x1*c+x0*s)*rope_attention_scaling);\n"
" } else if (d >= rope_dim) {\n"
" key_cache[key_dst_base+d]=source_key[key_src_base+d];\n"
" }\n"
" if (hydrate_value != 0) {\n"
" value_cache[value_dst]=source_value[value_src];\n"
" }\n"
"}\n"
"__kernel void export_canonical_paged_key(\n"
" __global const FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global FLOAT* key_out,// [kv_len,batch,kv_heads,head_dim]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int rope_dim_in,\n"
" const float rope_theta,\n"
" const int rope_type_llama3,\n"
" const float rope_scaling_factor,\n"
" const float rope_scaling_low_freq_factor,\n"
" const float rope_scaling_high_freq_factor,\n"
" const int rope_scaling_original_max_position_embeddings,\n"
" const int max_position_embeddings,\n"
" const float rope_attention_scaling,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int d=index % head_dim;\n"
" int t=index/head_dim;\n"
" int h=t % kv_heads;\n"
" t=t/kv_heads;\n"
" int b=t % batch;\n"
" int logical=t/batch;\n"
" if (logical >= kv_len) {\n"
" return;\n"
" }\n"
" int slot=slot_table[logical];\n"
" if (slot<0 || slot >= max_slots) {\n"
" return;\n"
" }\n"
" int src_base=((slot*batch+b)*kv_heads+h)*head_dim;\n"
" int dst=((logical*batch+b)*kv_heads+h)*head_dim+d;\n"
" float out=(float)key_cache[src_base+d];\n"
" int rope_dim=min(rope_dim_in>0 ? rope_dim_in : head_dim,head_dim);\n"
" rope_dim=(rope_dim/2)*2;\n"
" if (rope_dim>0 && d<rope_dim) {\n"
" int rope_half=rope_dim/2;\n"
" int pair=d<rope_half ? d : d-rope_half;\n"
" float inv_freq=paged_rope_inv_freq(\n"
" rope_theta>0.0f ? rope_theta : 10000.0f,\n"
" rope_type_llama3,\n"
" max(rope_scaling_factor,1.0f),\n"
" max(rope_scaling_low_freq_factor,1.0e-6f),\n"
" max(rope_scaling_high_freq_factor,1.0e-6f),\n"
" rope_scaling_original_max_position_embeddings>0 ? rope_scaling_original_max_position_embeddings\n"
" : max_position_embeddings,\n"
" pair,\n"
" rope_dim);\n"
" float angle=(float)logical*inv_freq;\n"
" float c=cos(angle);\n"
" float s=sin(angle);\n"
" float y0=(float)key_cache[src_base+pair];\n"
" float y1=(float)key_cache[src_base+pair+rope_half];\n"
" float inv_scale=rope_attention_scaling>0.0f ? 1.0f/rope_attention_scaling : 1.0f;\n"
" out=d<rope_half ? (y0*c+y1*s)*inv_scale : (y1*c-y0*s)*inv_scale;\n"
" }\n"
" key_out[dst]=(FLOAT)out;\n"
"}\n"
"__constant sampler_t PAGED_ATTENTION_IMAGE_SAMPLER =\n"
" CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;\n"
"inline FLOAT4 paged_attention_read_linear4_image(__read_only image2d_t image,\n"
" const int linear_index,\n"
" const int image_width) {\n"
" const int pixel0=linear_index >> 2;\n"
" const int2 coord0=(int2)(pixel0-(pixel0/image_width)*image_width,pixel0/image_width);\n"
" const FLOAT4 p0=RI_F(image,PAGED_ATTENTION_IMAGE_SAMPLER,coord0);\n"
" const int lane=linear_index & 3;\n"
" if (lane == 0) {\n"
" return p0;\n"
" }\n"
" const int pixel1=(linear_index+3) >> 2;\n"
" const int2 coord1=(int2)(pixel1-(pixel1/image_width)*image_width,pixel1/image_width);\n"
" const FLOAT4 p1=RI_F(image,PAGED_ATTENTION_IMAGE_SAMPLER,coord1);\n"
" if (lane == 1) {\n"
" return (FLOAT4)(p0.y,p0.z,p0.w,p1.x);\n"
" }\n"
" if (lane == 2) {\n"
" return (FLOAT4)(p0.z,p0.w,p1.x,p1.y);\n"
" }\n"
" return (FLOAT4)(p0.w,p1.x,p1.y,p1.z);\n"
"}\n"
"__kernel void pic_cacheblend_value_score(\n"
" __global const FLOAT* reference_value_cache,// [batch,kv_heads,max_slots,head_dim]\n"
" __global const FLOAT* cached_value_cache,// [batch,kv_heads,cached_max_slots,head_dim]\n"
" __global const int* slot_table,\n"
" __global float* scores,\n"
" const int batch,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int cached_max_slots,\n"
" const int cached_slot_start,\n"
" const int logical_start,\n"
" const int token_count,\n"
" const int score_offset) {\n"
" int token_local=get_global_id(0);\n"
" if (token_local >= token_count) {\n"
" return;\n"
" }\n"
" int logical=logical_start+token_local;\n"
" if (logical<0 || logical >= max_slots) {\n"
" scores[score_offset+token_local]=-3.4028234663852886e+38f;\n"
" return;\n"
" }\n"
" int slot=slot_table[logical];\n"
" int cached_slot=cached_slot_start+token_local;\n"
" if (slot<0 || slot >= max_slots || cached_slot<0 || cached_slot >= cached_max_slots) {\n"
" scores[score_offset+token_local]=-3.4028234663852886e+38f;\n"
" return;\n"
" }\n"
" float acc=0.0f;\n"
" for (int b=0; b<batch; ++b) {\n"
" for (int h=0; h<kv_heads; ++h) {\n"
" int ref_base=((b*kv_heads+h)*max_slots+slot)*head_dim;\n"
" int cached_base=((b*kv_heads+h)*cached_max_slots+cached_slot)*head_dim;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" acc += fabs((float)reference_value_cache[ref_base+d]-(float)cached_value_cache[cached_base+d]);\n"
" }\n"
" }\n"
" }\n"
" int denom_int=batch*kv_heads*head_dim;\n"
" float denom=(float)(denom_int>0 ? denom_int : 1);\n"
" scores[score_offset+token_local]=acc/denom;\n"
"}\n"
"__kernel void pic_cacheblend_value_score_cached_image(\n"
" __global const FLOAT* reference_value_cache,// [batch,kv_heads,max_slots,head_dim]\n"
" __read_only image2d_t cached_value_image,// linearized [batch*kv_heads,cached_token_stride,head_dim]\n"
" __global const int* slot_table,\n"
" __global float* scores,\n"
" const int batch,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int cached_token_stride,\n"
" const int cached_image_width,\n"
" const int logical_start,\n"
" const int token_count,\n"
" const int score_offset) {\n"
" int token_local=get_global_id(0);\n"
" if (token_local >= token_count) {\n"
" return;\n"
" }\n"
" int logical=logical_start+token_local;\n"
" if (logical<0 || logical >= max_slots) {\n"
" scores[score_offset+token_local]=-3.4028234663852886e+38f;\n"
" return;\n"
" }\n"
" int slot=slot_table[logical];\n"
" if (slot<0 || slot >= max_slots || cached_token_stride <= 0 || cached_image_width <= 0) {\n"
" scores[score_offset+token_local]=-3.4028234663852886e+38f;\n"
" return;\n"
" }\n"
" float acc=0.0f;\n"
" for (int b=0; b<batch; ++b) {\n"
" for (int h=0; h<kv_heads; ++h) {\n"
" int ref_base=((b*kv_heads+h)*max_slots+slot)*head_dim;\n"
" int cached_base=((b*kv_heads+h)*cached_token_stride+token_local)*head_dim;\n"
" int d=0;\n"
" for (; d+3<head_dim; d += 4) {\n"
" float4 ref4=convert_float4(vload4(0,reference_value_cache+ref_base+d));\n"
" float4 cached4=convert_float4(\n"
" paged_attention_read_linear4_image(cached_value_image,cached_base+d,cached_image_width));\n"
" float4 diff4=fabs(ref4-cached4);\n"
" acc += diff4.x+diff4.y+diff4.z+diff4.w;\n"
" }\n"
" if (d<head_dim) {\n"
" float4 cached4=convert_float4(\n"
" paged_attention_read_linear4_image(cached_value_image,cached_base+d,cached_image_width));\n"
" for (int tail=d; tail<head_dim; ++tail) {\n"
" int lane=tail-d;\n"
" float cached=lane == 0 ? cached4.x : (lane == 1 ? cached4.y : (lane == 2 ? cached4.z : cached4.w));\n"
" acc += fabs((float)reference_value_cache[ref_base+tail]-cached);\n"
" }\n"
" }\n"
" }\n"
" }\n"
" int denom_int=batch*kv_heads*head_dim;\n"
" float denom=(float)(denom_int>0 ? denom_int : 1);\n"
" scores[score_offset+token_local]=acc/denom;\n"
"}\n"
"__kernel void pic_cacheblend_topk(\n"
" __global const float* scores,\n"
" __global int* selected,\n"
" const int token_count,\n"
" const int top_k) {\n"
" const int lid=get_local_id(0);\n"
" const int local_size=get_local_size(0);\n"
" __local float best_values[1024];\n"
" __local int best_indices[1024];\n"
" if (get_group_id(0) != 0 || lid >= 1024) {\n"
" return;\n"
" }\n"
" if (token_count <= 1024) {\n"
" for (int i=lid; i<1024; i += local_size) {\n"
" float value=-3.4028234663852886e+38f;\n"
" int index=-1;\n"
" if (i<token_count) {\n"
" value=scores[i];\n"
" index=i;\n"
" if (isnan(value)) {\n"
" value=-3.4028234663852886e+38f;\n"
" }\n"
" }\n"
" best_values[i]=value;\n"
" best_indices[i]=index;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int k=2; k <= 1024; k <<= 1) {\n"
" for (int stride=k >> 1; stride>0; stride >>= 1) {\n"
" for (int i=lid; i<1024; i += local_size) {\n"
" int other=i ^ stride;\n"
" if (other>i) {\n"
" float value_i=best_values[i];\n"
" float value_o=best_values[other];\n"
" int index_i=best_indices[i];\n"
" int index_o=best_indices[other];\n"
" int other_better=(value_o>value_i) ||\n"
" (value_o == value_i && index_o >= 0 &&\n"
" (index_i<0 || index_o<index_i));\n"
" int self_better=(value_i>value_o) ||\n"
" (value_i == value_o && index_i >= 0 &&\n"
" (index_o<0 || index_i<index_o));\n"
" int descending=((i & k) == 0);\n"
" if ((descending && other_better) || (!descending && self_better)) {\n"
" best_values[i]=value_o;\n"
" best_indices[i]=index_o;\n"
" best_values[other]=value_i;\n"
" best_indices[other]=index_i;\n"
" }\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" }\n"
" for (int i=lid; i<top_k; i += local_size) {\n"
" selected[i]=best_indices[i];\n"
" }\n"
" return;\n"
" }\n"
" for (int k=0; k<top_k; ++k) {\n"
" float best=-3.4028234663852886e+38f;\n"
" int best_index=-1;\n"
" for (int i=lid; i<token_count; i += local_size) {\n"
" int used=0;\n"
" for (int prev=0; prev<k; ++prev) {\n"
" if (selected[prev] == i) {\n"
" used=1;\n"
" break;\n"
" }\n"
" }\n"
" if (used) {\n"
" continue;\n"
" }\n"
" float value=scores[i];\n"
" if (isnan(value)) {\n"
" value=-3.4028234663852886e+38f;\n"
" }\n"
" if (best_index<0 || value>best || (value == best && i<best_index)) {\n"
" best=value;\n"
" best_index=i;\n"
" }\n"
" }\n"
" best_values[lid]=best;\n"
" best_indices[lid]=best_index;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int stride=local_size >> 1; stride>0; stride >>= 1) {\n"
" if (lid<stride) {\n"
" float other_value=best_values[lid+stride];\n"
" int other_index=best_indices[lid+stride];\n"
" if (other_value>best_values[lid] ||\n"
" (other_value == best_values[lid] && other_index >= 0 &&\n"
" (best_indices[lid]<0 || other_index<best_indices[lid]))) {\n"
" best_values[lid]=other_value;\n"
" best_indices[lid]=other_index;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" selected[k]=best_indices[0];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE);\n"
" }\n"
"}\n"
"__kernel void pic_cacheblend_topk_stage1(\n"
" __global const float* scores,\n"
" __global float* stage_values,\n"
" __global int* stage_indices,\n"
" const int token_count,\n"
" const int top_k,\n"
" const int block_size,\n"
" __local float* best_values,\n"
" __local int* best_indices) {\n"
" const int lid=get_local_id(0);\n"
" const int local_size=get_local_size(0);\n"
" const int group=get_group_id(0);\n"
" if (block_size <= 0) {\n"
" return;\n"
" }\n"
" const int block_start=group*block_size;\n"
" for (int i=lid; i<block_size; i += local_size) {\n"
" const int index=block_start+i;\n"
" float value=-3.4028234663852886e+38f;\n"
" int out_index=-1;\n"
" if (index<token_count) {\n"
" value=scores[index];\n"
" out_index=index;\n"
" if (isnan(value)) {\n"
" value=-3.4028234663852886e+38f;\n"
" }\n"
" }\n"
" best_values[i]=value;\n"
" best_indices[i]=out_index;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int k=2; k <= block_size; k <<= 1) {\n"
" for (int stride=k >> 1; stride>0; stride >>= 1) {\n"
" for (int i=lid; i<block_size; i += local_size) {\n"
" const int other=i ^ stride;\n"
" if (other>i) {\n"
" const float value_i=best_values[i];\n"
" const float value_o=best_values[other];\n"
" const int index_i=best_indices[i];\n"
" const int index_o=best_indices[other];\n"
" const int other_better=(value_o>value_i) ||\n"
" (value_o == value_i && index_o >= 0 &&\n"
" (index_i<0 || index_o<index_i));\n"
" const int self_better=(value_i>value_o) ||\n"
" (value_i == value_o && index_i >= 0 &&\n"
" (index_o<0 || index_i<index_o));\n"
" const int descending=((i & k) == 0);\n"
" if ((descending && other_better) || (!descending && self_better)) {\n"
" best_values[i]=value_o;\n"
" best_indices[i]=index_o;\n"
" best_values[other]=value_i;\n"
" best_indices[other]=index_i;\n"
" }\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" }\n"
" const int candidate_offset=group*top_k;\n"
" for (int i=lid; i<top_k; i += local_size) {\n"
" stage_values[candidate_offset+i]=best_values[i];\n"
" stage_indices[candidate_offset+i]=best_indices[i];\n"
" }\n"
"}\n"
"__kernel void pic_cacheblend_topk_stage2(\n"
" __global const float* stage_values,\n"
" __global const int* stage_indices,\n"
" __global int* selected,\n"
" const int candidate_count,\n"
" const int top_k,\n"
" const int sort_size,\n"
" __local float* best_values,\n"
" __local int* best_indices) {\n"
" const int lid=get_local_id(0);\n"
" const int local_size=get_local_size(0);\n"
" if (get_group_id(0) != 0 || sort_size <= 0) {\n"
" return;\n"
" }\n"
" for (int i=lid; i<sort_size; i += local_size) {\n"
" float value=-3.4028234663852886e+38f;\n"
" int index=-1;\n"
" if (i<candidate_count) {\n"
" value=stage_values[i];\n"
" index=stage_indices[i];\n"
" if (isnan(value)) {\n"
" value=-3.4028234663852886e+38f;\n"
" }\n"
" }\n"
" best_values[i]=value;\n"
" best_indices[i]=index;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int k=2; k <= sort_size; k <<= 1) {\n"
" for (int stride=k >> 1; stride>0; stride >>= 1) {\n"
" for (int i=lid; i<sort_size; i += local_size) {\n"
" const int other=i ^ stride;\n"
" if (other>i) {\n"
" const float value_i=best_values[i];\n"
" const float value_o=best_values[other];\n"
" const int index_i=best_indices[i];\n"
" const int index_o=best_indices[other];\n"
" const int other_better=(value_o>value_i) ||\n"
" (value_o == value_i && index_o >= 0 &&\n"
" (index_i<0 || index_o<index_i));\n"
" const int self_better=(value_i>value_o) ||\n"
" (value_i == value_o && index_i >= 0 &&\n"
" (index_o<0 || index_i<index_o));\n"
" const int descending=((i & k) == 0);\n"
" if ((descending && other_better) || (!descending && self_better)) {\n"
" best_values[i]=value_o;\n"
" best_indices[i]=index_o;\n"
" best_values[other]=value_i;\n"
" best_indices[other]=index_i;\n"
" }\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" }\n"
" for (int i=lid; i<top_k; i += local_size) {\n"
" selected[i]=best_indices[i];\n"
" }\n"
"}\n"
"__kernel void paged_attention_row(\n"
" __global const FLOAT* query,\n"
" __global const FLOAT* key_cache,\n"
" __global const FLOAT* value_cache,\n"
" __global FLOAT* output,\n"
" __global const FLOAT* mask,\n"
" __global const int* slot_table,\n"
" __global const int* sparse_query,\n"
" const int mask_elements,\n"
" const int batch,\n"
" const int query_len,\n"
" const int output_len,\n"
" const int attn_len,\n"
" const int num_heads,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int base_logical,\n"
" const int kv_len,\n"
" const int max_slots,\n"
" const float scale,\n"
" const int sparse_active,\n"
" const int query_rows_are_full,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int h=index % num_heads;\n"
" int t=index/num_heads;\n"
" int q=t % attn_len;\n"
" int b=t/attn_len;\n"
" int group=num_heads/kv_heads;\n"
" int kv_head=h/group;\n"
" int q_logical=sparse_active ? sparse_query[q] : (base_logical+q);\n"
" int q_row=query_rows_are_full ? q_logical : q;\n"
" int valid_len=min(kv_len,q_logical+1);\n"
" if (valid_len <= 0 || head_dim>256) {\n"
" return;\n"
" }\n"
" float max_score=-3.4028234663852886e+38f;\n"
" for (int k=0; k<valid_len; ++k) {\n"
" int slot=slot_table[k];\n"
" if (slot<0 || slot >= max_slots) {\n"
" continue;\n"
" }\n"
" float score=0.0f;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" int q_offset=((b*query_len+q_row)*num_heads+h)*head_dim+d;\n"
" int k_offset=((slot*batch+b)*kv_heads+kv_head)*head_dim+d;\n"
" score += (float)query[q_offset]*(float)key_cache[k_offset];\n"
" }\n"
" score *= scale;\n"
" if (mask_elements>1) {\n"
" int mask_cols=mask_elements >= attn_len*kv_len ? kv_len : attn_len;\n"
" int gap=kv_len-mask_cols;\n"
" int col=k-gap;\n"
" int mask_row=query_rows_are_full ? q_logical : q;\n"
" int mask_index=mask_row*mask_cols+col;\n"
" if (col >= 0 && col<mask_cols && mask_index >= 0 && mask_index<mask_elements) {\n"
" score += (float)mask[mask_index];\n"
" }\n"
" }\n"
" max_score=fmax(max_score,score);\n"
" }\n"
" float acc[256];\n"
" for (int d=0; d<head_dim; ++d) {\n"
" acc[d]=0.0f;\n"
" }\n"
" float sum=0.0f;\n"
" for (int k=0; k<valid_len; ++k) {\n"
" int slot=slot_table[k];\n"
" if (slot<0 || slot >= max_slots) {\n"
" continue;\n"
" }\n"
" float score=0.0f;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" int q_offset=((b*query_len+q_row)*num_heads+h)*head_dim+d;\n"
" int k_offset=((slot*batch+b)*kv_heads+kv_head)*head_dim+d;\n"
" score += (float)query[q_offset]*(float)key_cache[k_offset];\n"
" }\n"
" score *= scale;\n"
" if (mask_elements>1) {\n"
" int mask_cols=mask_elements >= attn_len*kv_len ? kv_len : attn_len;\n"
" int gap=kv_len-mask_cols;\n"
" int col=k-gap;\n"
" int mask_row=query_rows_are_full ? q_logical : q;\n"
" int mask_index=mask_row*mask_cols+col;\n"
" if (col >= 0 && col<mask_cols && mask_index >= 0 && mask_index<mask_elements) {\n"
" score += (float)mask[mask_index];\n"
" }\n"
" }\n"
" float weight=exp(score-max_score);\n"
" sum += weight;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" int v_offset=((b*kv_heads+kv_head)*max_slots+slot)*head_dim+d;\n"
" acc[d] += weight*(float)value_cache[v_offset];\n"
" }\n"
" }\n"
" float inv_sum=sum>0.0f ? 1.0f/sum : 0.0f;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" output[((b*output_len+q)*num_heads+h)*head_dim+d]=(FLOAT)(acc[d]*inv_sum);\n"
" }\n"
"}\n"
"__kernel void paged_attention(\n"
" __global const FLOAT* query,\n"
" __global const FLOAT* key_cache,\n"
" __global const FLOAT* value_cache,\n"
" __global FLOAT* output,\n"
" __global const FLOAT* mask,\n"
" __global const int* slot_table,\n"
" __global const int* sparse_query,\n"
" const int mask_elements,\n"
" const int batch,\n"
" const int query_len,\n"
" const int output_len,\n"
" const int attn_len,\n"
" const int num_heads,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int base_logical,\n"
" const int kv_len,\n"
" const int max_slots,\n"
" const float scale,\n"
" const int sparse_active,\n"
" const int query_rows_are_full,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int d=index % head_dim;\n"
" int t=index/head_dim;\n"
" int h=t % num_heads;\n"
" t=t/num_heads;\n"
" int q=t % attn_len;\n"
" int b=t/attn_len;\n"
" int group=num_heads/kv_heads;\n"
" int kv_head=h/group;\n"
" int q_logical=sparse_active ? sparse_query[q] : (base_logical+q);\n"
" int q_row=query_rows_are_full ? q_logical : q;\n"
" int valid_len=min(kv_len,q_logical+1);\n"
" if (valid_len <= 0) {\n"
" output[((b*output_len+q)*num_heads+h)*head_dim+d]=(FLOAT)0;\n"
" return;\n"
" }\n"
" float max_score=-3.4028234663852886e+38f;\n"
" for (int k=0; k<valid_len; ++k) {\n"
" int slot=slot_table[k];\n"
" float score=0.0f;\n"
" for (int kd=0; kd<head_dim; ++kd) {\n"
" int q_offset=((b*query_len+q_row)*num_heads+h)*head_dim+kd;\n"
" int k_offset=((slot*batch+b)*kv_heads+kv_head)*head_dim+kd;\n"
" score += (float)query[q_offset]*(float)key_cache[k_offset];\n"
" }\n"
" score *= scale;\n"
" if (mask_elements>1) {\n"
" int mask_cols=mask_elements >= attn_len*kv_len ? kv_len : attn_len;\n"
" int gap=kv_len-mask_cols;\n"
" int col=k-gap;\n"
" int mask_row=query_rows_are_full ? q_logical : q;\n"
" int mask_index=mask_row*mask_cols+col;\n"
" if (col >= 0 && col<mask_cols && mask_index >= 0 && mask_index<mask_elements) {\n"
" score += (float)mask[mask_index];\n"
" }\n"
" }\n"
" max_score=fmax(max_score,score);\n"
" }\n"
" float sum=0.0f;\n"
" float acc=0.0f;\n"
" for (int k=0; k<valid_len; ++k) {\n"
" int slot=slot_table[k];\n"
" float score=0.0f;\n"
" for (int kd=0; kd<head_dim; ++kd) {\n"
" int q_offset=((b*query_len+q_row)*num_heads+h)*head_dim+kd;\n"
" int k_offset=((slot*batch+b)*kv_heads+kv_head)*head_dim+kd;\n"
" score += (float)query[q_offset]*(float)key_cache[k_offset];\n"
" }\n"
" score *= scale;\n"
" if (mask_elements>1) {\n"
" int mask_cols=mask_elements >= attn_len*kv_len ? kv_len : attn_len;\n"
" int gap=kv_len-mask_cols;\n"
" int col=k-gap;\n"
" int mask_row=query_rows_are_full ? q_logical : q;\n"
" int mask_index=mask_row*mask_cols+col;\n"
" if (col >= 0 && col<mask_cols && mask_index >= 0 && mask_index<mask_elements) {\n"
" score += (float)mask[mask_index];\n"
" }\n"
" }\n"
" float weight=exp(score-max_score);\n"
" int v_offset=((b*kv_heads+kv_head)*max_slots+slot)*head_dim+d;\n"
" acc += weight*(float)value_cache[v_offset];\n"
" sum += weight;\n"
" }\n"
" output[((b*output_len+q)*num_heads+h)*head_dim+d]=(FLOAT)(sum>0.0f ? acc/sum : 0.0f);\n"
"}\n"
;
#endif
}
