#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* paged_attention_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"__kernel void zero_output(\n"
" __global FLOAT* output,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" output[index]=(FLOAT)0;\n"
"}\n"
"__kernel void copy_paged_kv(\n"
" __global const FLOAT* key,\n"
" __global const FLOAT* value,\n"
" __global FLOAT* key_cache,\n"
" __global FLOAT* value_cache,\n"
" __global const int* slot_table,\n"
" __global const int* sparse_query,\n"
" const int batch,\n"
" const int new_kv_len,\n"
" const int insert_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int base_logical,\n"
" const int max_slots,\n"
" const int sparse_active,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int d=index % head_dim;\n"
" int t=index/head_dim;\n"
" int h=t % kv_heads;\n"
" t=t/kv_heads;\n"
" int l=t % insert_len;\n"
" int b=t/insert_len;\n"
" int logical=sparse_active ? sparse_query[l] : (base_logical+l);\n"
" if (logical<0) {\n"
" return;\n"
" }\n"
" int slot=slot_table[logical];\n"
" if (slot<0 || slot >= max_slots || l >= new_kv_len) {\n"
" return;\n"
" }\n"
" int in_offset=((b*new_kv_len+l)*kv_heads+h)*head_dim+d;\n"
" int k_offset=((slot*batch+b)*kv_heads+h)*head_dim+d;\n"
" int v_offset=((b*kv_heads+h)*max_slots+slot)*head_dim+d;\n"
" key_cache[k_offset]=key[in_offset];\n"
" value_cache[v_offset]=value[in_offset];\n"
"}\n"
"__kernel void pack_paged_kv_prefill(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global const FLOAT* value_cache,// [batch,kv_heads,max_slots,head_dim]\n"
" __global FLOAT* packed_key,// [batch*kv_heads,head_dim_pack,kv_len_pack]\n"
" __global FLOAT* packed_value,// [batch*kv_heads,kv_len_pack,head_dim_pack]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots) {\n"
" const int x=get_global_id(0); // kv token/4\n"
" const int y=get_global_id(1); // head dim/4\n"
" int z=get_global_id(2); // batch*kv_heads\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int logical4=x << 2;\n"
" const int dim4=y << 2;\n"
" const int head_dim_pack=((head_dim+3)/4)*4;\n"
" const int kv_len_pack=((kv_len+3)/4)*4;\n"
" const int b=z/kv_heads;\n"
" const int h=z-b*kv_heads;\n"
" FLOAT4 k0=(FLOAT4)0;\n"
" FLOAT4 k1=(FLOAT4)0;\n"
" FLOAT4 k2=(FLOAT4)0;\n"
" FLOAT4 k3=(FLOAT4)0;\n"
" FLOAT4 v0=(FLOAT4)0;\n"
" FLOAT4 v1=(FLOAT4)0;\n"
" FLOAT4 v2=(FLOAT4)0;\n"
" FLOAT4 v3=(FLOAT4)0;\n"
" if (dim4<head_dim) {\n"
" int slot0=logical4<kv_len ? slot_table[logical4] : -1;\n"
" int slot1=logical4+1<kv_len ? slot_table[logical4+1] : -1;\n"
" int slot2=logical4+2<kv_len ? slot_table[logical4+2] : -1;\n"
" int slot3=logical4+3<kv_len ? slot_table[logical4+3] : -1;\n"
" if (slot0 >= 0 && slot0<max_slots) {\n"
" k0=vload4(0,key_cache+((slot0*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v0=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot0)*head_dim+dim4);\n"
" }\n"
" if (slot1 >= 0 && slot1<max_slots) {\n"
" k1=vload4(0,key_cache+((slot1*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v1=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot1)*head_dim+dim4);\n"
" }\n"
" if (slot2 >= 0 && slot2<max_slots) {\n"
" k2=vload4(0,key_cache+((slot2*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v2=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot2)*head_dim+dim4);\n"
" }\n"
" if (slot3 >= 0 && slot3<max_slots) {\n"
" k3=vload4(0,key_cache+((slot3*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" v3=vload4(0,value_cache+((b*kv_heads+h)*max_slots+slot3)*head_dim+dim4);\n"
" }\n"
" if (dim4+3 >= head_dim) {\n"
" if (dim4+1 >= head_dim) {\n"
" k0.yzw=(FLOAT3)0; k1.yzw=(FLOAT3)0; k2.yzw=(FLOAT3)0; k3.yzw=(FLOAT3)0;\n"
" v0.yzw=(FLOAT3)0; v1.yzw=(FLOAT3)0; v2.yzw=(FLOAT3)0; v3.yzw=(FLOAT3)0;\n"
" } else if (dim4+2 >= head_dim) {\n"
" k0.zw=(FLOAT2)0; k1.zw=(FLOAT2)0; k2.zw=(FLOAT2)0; k3.zw=(FLOAT2)0;\n"
" v0.zw=(FLOAT2)0; v1.zw=(FLOAT2)0; v2.zw=(FLOAT2)0; v3.zw=(FLOAT2)0;\n"
" } else {\n"
" k0.w=(FLOAT)0; k1.w=(FLOAT)0; k2.w=(FLOAT)0; k3.w=(FLOAT)0;\n"
" v0.w=(FLOAT)0; v1.w=(FLOAT)0; v2.w=(FLOAT)0; v3.w=(FLOAT)0;\n"
" }\n"
" }\n"
" }\n"
" const int key_offset=(z*head_dim_pack+dim4)*kv_len_pack+logical4;\n"
" vstore4((FLOAT4)(k0.s0,k1.s0,k2.s0,k3.s0),0,packed_key+key_offset);\n"
" vstore4((FLOAT4)(k0.s1,k1.s1,k2.s1,k3.s1),0,packed_key+key_offset+kv_len_pack);\n"
" vstore4((FLOAT4)(k0.s2,k1.s2,k2.s2,k3.s2),0,packed_key+key_offset+kv_len_pack*2);\n"
" vstore4((FLOAT4)(k0.s3,k1.s3,k2.s3,k3.s3),0,packed_key+key_offset+kv_len_pack*3);\n"
" const int value_offset=(z*kv_len_pack+logical4)*head_dim_pack+dim4;\n"
" vstore4(v0,0,packed_value+value_offset);\n"
" vstore4(v1,0,packed_value+value_offset+head_dim_pack);\n"
" vstore4(v2,0,packed_value+value_offset+head_dim_pack*2);\n"
" vstore4(v3,0,packed_value+value_offset+head_dim_pack*3);\n"
"}\n"
"__kernel void pack_paged_k_prefill(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global FLOAT* packed_key,// [batch*kv_heads,head_dim_pack,kv_len_pack]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots) {\n"
" const int x=get_global_id(0); // kv token/4\n"
" const int y=get_global_id(1); // head dim/4\n"
" int z=get_global_id(2); // batch*kv_heads\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int logical4=x << 2;\n"
" const int dim4=y << 2;\n"
" const int head_dim_pack=((head_dim+3)/4)*4;\n"
" const int kv_len_pack=((kv_len+3)/4)*4;\n"
" const int b=z/kv_heads;\n"
" const int h=z-b*kv_heads;\n"
" FLOAT4 k0=(FLOAT4)0;\n"
" FLOAT4 k1=(FLOAT4)0;\n"
" FLOAT4 k2=(FLOAT4)0;\n"
" FLOAT4 k3=(FLOAT4)0;\n"
" if (dim4<head_dim) {\n"
" int slot0=logical4<kv_len ? slot_table[logical4] : -1;\n"
" int slot1=logical4+1<kv_len ? slot_table[logical4+1] : -1;\n"
" int slot2=logical4+2<kv_len ? slot_table[logical4+2] : -1;\n"
" int slot3=logical4+3<kv_len ? slot_table[logical4+3] : -1;\n"
" if (slot0 >= 0 && slot0<max_slots) {\n"
" k0=vload4(0,key_cache+((slot0*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot1 >= 0 && slot1<max_slots) {\n"
" k1=vload4(0,key_cache+((slot1*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot2 >= 0 && slot2<max_slots) {\n"
" k2=vload4(0,key_cache+((slot2*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (slot3 >= 0 && slot3<max_slots) {\n"
" k3=vload4(0,key_cache+((slot3*batch+b)*kv_heads+h)*head_dim+dim4);\n"
" }\n"
" if (dim4+3 >= head_dim) {\n"
" if (dim4+1 >= head_dim) {\n"
" k0.yzw=(FLOAT3)0; k1.yzw=(FLOAT3)0; k2.yzw=(FLOAT3)0; k3.yzw=(FLOAT3)0;\n"
" } else if (dim4+2 >= head_dim) {\n"
" k0.zw=(FLOAT2)0; k1.zw=(FLOAT2)0; k2.zw=(FLOAT2)0; k3.zw=(FLOAT2)0;\n"
" } else {\n"
" k0.w=(FLOAT)0; k1.w=(FLOAT)0; k2.w=(FLOAT)0; k3.w=(FLOAT)0;\n"
" }\n"
" }\n"
" }\n"
" const int key_offset=(z*head_dim_pack+dim4)*kv_len_pack+logical4;\n"
" vstore4((FLOAT4)(k0.s0,k1.s0,k2.s0,k3.s0),0,packed_key+key_offset);\n"
" vstore4((FLOAT4)(k0.s1,k1.s1,k2.s1,k3.s1),0,packed_key+key_offset+kv_len_pack);\n"
" vstore4((FLOAT4)(k0.s2,k1.s2,k2.s2,k3.s2),0,packed_key+key_offset+kv_len_pack*2);\n"
" vstore4((FLOAT4)(k0.s3,k1.s3,k2.s3,k3.s3),0,packed_key+key_offset+kv_len_pack*3);\n"
"}\n"
"static inline float paged_rope_inv_freq(\n"
" const float theta,\n"
" const int rope_type_llama3,\n"
" const float factor,\n"
" const float low_freq_factor,\n"
" const float high_freq_factor,\n"
" const int old_context,\n"
" const int pair_index,\n"
" const int rope_dim) {\n"
" float inv_freq=pow(theta,-((float)(2*pair_index))/(float)rope_dim);\n"
" if (rope_type_llama3 == 0 || old_context <= 0 || factor == 1.0f || low_freq_factor == high_freq_factor) {\n"
" return inv_freq;\n"
" }\n"
" const float two_pi=6.28318530717958647692f;\n"
" const float wavelen=two_pi/inv_freq;\n"
" const float low_freq_wavelen=(float)old_context/low_freq_factor;\n"
" const float high_freq_wavelen=(float)old_context/high_freq_factor;\n"
" float scaled=wavelen>low_freq_wavelen ? inv_freq/factor : inv_freq;\n"
" if (wavelen >= high_freq_wavelen && wavelen <= low_freq_wavelen) {\n"
" const float smooth=((float)old_context/wavelen-low_freq_factor)/(high_freq_factor-low_freq_factor);\n"
" scaled=(1.0f-smooth)*inv_freq/factor+smooth*inv_freq;\n"
" }\n"
" return scaled;\n"
"}\n"
"__kernel void pic_page_attention_hydrate_kv(\n"
" __global const FLOAT* source_key,// [token_count,batch,kv_heads,head_dim]\n"
" __global const FLOAT* source_value,// [batch,kv_heads,token_count,head_dim]\n"
" __global FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global FLOAT* value_cache,// [batch,kv_heads,max_slots,head_dim]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int logical_start,\n"
" const int token_count,\n"
" const int key_source_logical_start,\n"
" const int hydrate_value,\n"
" const int rope_dim_in,\n"
" const float rope_theta,\n"
" const int rope_type_llama3,\n"
" const float rope_scaling_factor,\n"
" const float rope_scaling_low_freq_factor,\n"
" const float rope_scaling_high_freq_factor,\n"
" const int rope_scaling_original_max_position_embeddings,\n"
" const int max_position_embeddings,\n"
" const float rope_attention_scaling,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int d=index % head_dim;\n"
" int t=index/head_dim;\n"
" int h=t % kv_heads;\n"
" t=t/kv_heads;\n"
" int b=t % batch;\n"
" int local_index=t/batch;\n"
" if (local_index >= token_count) {\n"
" return;\n"
" }\n"
" int logical=logical_start+local_index;\n"
" int slot=slot_table[logical];\n"
" if (slot<0 || slot >= max_slots) {\n"
" return;\n"
" }\n"
" int source_token=key_source_logical_start+local_index;\n"
" if (source_token<0 || source_token >= token_count) {\n"
" if (key_source_logical_start <= 0) {\n"
" return;\n"
" }\n"
" if (source_token >= max_slots) {\n"
" return;\n"
" }\n"
" }\n"
" int value_source_token=local_index;\n"
" if (value_source_token<0 || value_source_token >= token_count) {\n"
" return;\n"
" }\n"
" int key_src_base=((source_token*batch+b)*kv_heads+h)*head_dim;\n"
" int key_dst_base=((slot*batch+b)*kv_heads+h)*head_dim;\n"
" int value_src=((b*kv_heads+h)*token_count+value_source_token)*head_dim+d;\n"
" int value_dst=((b*kv_heads+h)*max_slots+slot)*head_dim+d;\n"
" int rope_dim=min(rope_dim_in>0 ? rope_dim_in : head_dim,head_dim);\n"
" rope_dim=(rope_dim/2)*2;\n"
" int rope_half=rope_dim/2;\n"
" if (d<rope_half) {\n"
" int pair=d;\n"
" float inv_freq=paged_rope_inv_freq(\n"
" rope_theta>0.0f ? rope_theta : 10000.0f,\n"
" rope_type_llama3,\n"
" max(rope_scaling_factor,1.0f),\n"
" max(rope_scaling_low_freq_factor,1.0e-6f),\n"
" max(rope_scaling_high_freq_factor,1.0e-6f),\n"
" rope_scaling_original_max_position_embeddings>0 ? rope_scaling_original_max_position_embeddings\n"
" : max_position_embeddings,\n"
" pair,\n"
" rope_dim);\n"
" float angle=(float)logical*inv_freq;\n"
" float c=cos(angle);\n"
" float s=sin(angle);\n"
" float x0=(float)source_key[key_src_base+pair];\n"
" float x1=(float)source_key[key_src_base+pair+rope_half];\n"
" key_cache[key_dst_base+pair]=(FLOAT)((x0*c-x1*s)*rope_attention_scaling);\n"
" key_cache[key_dst_base+pair+rope_half]=(FLOAT)((x1*c+x0*s)*rope_attention_scaling);\n"
" } else if (d >= rope_dim) {\n"
" key_cache[key_dst_base+d]=source_key[key_src_base+d];\n"
" }\n"
" if (hydrate_value != 0) {\n"
" value_cache[value_dst]=source_value[value_src];\n"
" }\n"
"}\n"
"__kernel void export_canonical_paged_key(\n"
" __global const FLOAT* key_cache,// [max_slots,batch,kv_heads,head_dim]\n"
" __global FLOAT* key_out,// [kv_len,batch,kv_heads,head_dim]\n"
" __global const int* slot_table,\n"
" const int batch,\n"
" const int kv_len,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int rope_dim_in,\n"
" const float rope_theta,\n"
" const int rope_type_llama3,\n"
" const float rope_scaling_factor,\n"
" const float rope_scaling_low_freq_factor,\n"
" const float rope_scaling_high_freq_factor,\n"
" const int rope_scaling_original_max_position_embeddings,\n"
" const int max_position_embeddings,\n"
" const float rope_attention_scaling,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int d=index % head_dim;\n"
" int t=index/head_dim;\n"
" int h=t % kv_heads;\n"
" t=t/kv_heads;\n"
" int b=t % batch;\n"
" int logical=t/batch;\n"
" if (logical >= kv_len) {\n"
" return;\n"
" }\n"
" int slot=slot_table[logical];\n"
" if (slot<0 || slot >= max_slots) {\n"
" return;\n"
" }\n"
" int src_base=((slot*batch+b)*kv_heads+h)*head_dim;\n"
" int dst=((logical*batch+b)*kv_heads+h)*head_dim+d;\n"
" float out=(float)key_cache[src_base+d];\n"
" int rope_dim=min(rope_dim_in>0 ? rope_dim_in : head_dim,head_dim);\n"
" rope_dim=(rope_dim/2)*2;\n"
" if (rope_dim>0 && d<rope_dim) {\n"
" int rope_half=rope_dim/2;\n"
" int pair=d<rope_half ? d : d-rope_half;\n"
" float inv_freq=paged_rope_inv_freq(\n"
" rope_theta>0.0f ? rope_theta : 10000.0f,\n"
" rope_type_llama3,\n"
" max(rope_scaling_factor,1.0f),\n"
" max(rope_scaling_low_freq_factor,1.0e-6f),\n"
" max(rope_scaling_high_freq_factor,1.0e-6f),\n"
" rope_scaling_original_max_position_embeddings>0 ? rope_scaling_original_max_position_embeddings\n"
" : max_position_embeddings,\n"
" pair,\n"
" rope_dim);\n"
" float angle=(float)logical*inv_freq;\n"
" float c=cos(angle);\n"
" float s=sin(angle);\n"
" float y0=(float)key_cache[src_base+pair];\n"
" float y1=(float)key_cache[src_base+pair+rope_half];\n"
" float inv_scale=rope_attention_scaling>0.0f ? 1.0f/rope_attention_scaling : 1.0f;\n"
" out=d<rope_half ? (y0*c+y1*s)*inv_scale : (y1*c-y0*s)*inv_scale;\n"
" }\n"
" key_out[dst]=(FLOAT)out;\n"
"}\n"
"__kernel void pic_cacheblend_value_score(\n"
" __global const FLOAT* reference_value_cache,// [batch,kv_heads,max_slots,head_dim]\n"
" __global const FLOAT* cached_value,// [batch,kv_heads,token_count,head_dim]\n"
" __global const int* slot_table,\n"
" __global float* scores,\n"
" const int batch,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int max_slots,\n"
" const int logical_start,\n"
" const int token_count,\n"
" const int score_offset) {\n"
" int token_local=get_global_id(0);\n"
" if (token_local >= token_count) {\n"
" return;\n"
" }\n"
" int logical=logical_start+token_local;\n"
" if (logical<0 || logical >= max_slots) {\n"
" scores[score_offset+token_local]=-3.4028234663852886e+38f;\n"
" return;\n"
" }\n"
" int slot=slot_table[logical];\n"
" if (slot<0 || slot >= max_slots) {\n"
" scores[score_offset+token_local]=-3.4028234663852886e+38f;\n"
" return;\n"
" }\n"
" float acc=0.0f;\n"
" for (int b=0; b<batch; ++b) {\n"
" for (int h=0; h<kv_heads; ++h) {\n"
" int ref_base=((b*kv_heads+h)*max_slots+slot)*head_dim;\n"
" int cached_base=((b*kv_heads+h)*token_count+token_local)*head_dim;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" acc += fabs((float)reference_value_cache[ref_base+d]-(float)cached_value[cached_base+d]);\n"
" }\n"
" }\n"
" }\n"
" int denom_int=batch*kv_heads*head_dim;\n"
" float denom=(float)(denom_int>0 ? denom_int : 1);\n"
" scores[score_offset+token_local]=acc/denom;\n"
"}\n"
"__kernel void pic_cacheblend_topk(\n"
" __global const float* scores,\n"
" __global int* selected,\n"
" const int token_count,\n"
" const int top_k) {\n"
" const int lid=get_local_id(0);\n"
" const int local_size=get_local_size(0);\n"
" __local float best_values[128];\n"
" __local int best_indices[128];\n"
" if (get_group_id(0) != 0 || lid >= 128) {\n"
" return;\n"
" }\n"
" for (int k=0; k<top_k; ++k) {\n"
" float best=-3.4028234663852886e+38f;\n"
" int best_index=-1;\n"
" for (int i=lid; i<token_count; i += local_size) {\n"
" int used=0;\n"
" for (int prev=0; prev<k; ++prev) {\n"
" if (selected[prev] == i) {\n"
" used=1;\n"
" break;\n"
" }\n"
" }\n"
" if (used) {\n"
" continue;\n"
" }\n"
" float value=scores[i];\n"
" if (isnan(value)) {\n"
" value=-3.4028234663852886e+38f;\n"
" }\n"
" if (best_index<0 || value>best || (value == best && i<best_index)) {\n"
" best=value;\n"
" best_index=i;\n"
" }\n"
" }\n"
" best_values[lid]=best;\n"
" best_indices[lid]=best_index;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int stride=local_size >> 1; stride>0; stride >>= 1) {\n"
" if (lid<stride) {\n"
" float other_value=best_values[lid+stride];\n"
" int other_index=best_indices[lid+stride];\n"
" if (other_value>best_values[lid] ||\n"
" (other_value == best_values[lid] && other_index >= 0 &&\n"
" (best_indices[lid]<0 || other_index<best_indices[lid]))) {\n"
" best_values[lid]=other_value;\n"
" best_indices[lid]=other_index;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" selected[k]=best_indices[0];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE);\n"
" }\n"
"}\n"
"__kernel void paged_attention_row(\n"
" __global const FLOAT* query,\n"
" __global const FLOAT* key_cache,\n"
" __global const FLOAT* value_cache,\n"
" __global FLOAT* output,\n"
" __global const FLOAT* mask,\n"
" __global const int* slot_table,\n"
" __global const int* sparse_query,\n"
" const int mask_elements,\n"
" const int batch,\n"
" const int query_len,\n"
" const int insert_len,\n"
" const int num_heads,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int base_logical,\n"
" const int kv_len,\n"
" const int max_slots,\n"
" const float scale,\n"
" const int sparse_active,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int h=index % num_heads;\n"
" int t=index/num_heads;\n"
" int q=t % insert_len;\n"
" int b=t/insert_len;\n"
" int group=num_heads/kv_heads;\n"
" int kv_head=h/group;\n"
" int q_logical=sparse_active ? sparse_query[q] : (base_logical+q);\n"
" int valid_len=min(kv_len,q_logical+1);\n"
" if (valid_len <= 0 || head_dim>256) {\n"
" return;\n"
" }\n"
" float max_score=-3.4028234663852886e+38f;\n"
" for (int k=0; k<valid_len; ++k) {\n"
" int slot=slot_table[k];\n"
" if (slot<0 || slot >= max_slots) {\n"
" continue;\n"
" }\n"
" float score=0.0f;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" int q_offset=((b*query_len+q)*num_heads+h)*head_dim+d;\n"
" int k_offset=((slot*batch+b)*kv_heads+kv_head)*head_dim+d;\n"
" score += (float)query[q_offset]*(float)key_cache[k_offset];\n"
" }\n"
" score *= scale;\n"
" if (mask_elements>1) {\n"
" int mask_cols=mask_elements >= insert_len*kv_len ? kv_len : insert_len;\n"
" int gap=kv_len-mask_cols;\n"
" int col=k-gap;\n"
" int mask_index=q*mask_cols+col;\n"
" if (col >= 0 && col<mask_cols && mask_index >= 0 && mask_index<mask_elements) {\n"
" score += (float)mask[mask_index];\n"
" }\n"
" }\n"
" max_score=fmax(max_score,score);\n"
" }\n"
" float acc[256];\n"
" for (int d=0; d<head_dim; ++d) {\n"
" acc[d]=0.0f;\n"
" }\n"
" float sum=0.0f;\n"
" for (int k=0; k<valid_len; ++k) {\n"
" int slot=slot_table[k];\n"
" if (slot<0 || slot >= max_slots) {\n"
" continue;\n"
" }\n"
" float score=0.0f;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" int q_offset=((b*query_len+q)*num_heads+h)*head_dim+d;\n"
" int k_offset=((slot*batch+b)*kv_heads+kv_head)*head_dim+d;\n"
" score += (float)query[q_offset]*(float)key_cache[k_offset];\n"
" }\n"
" score *= scale;\n"
" if (mask_elements>1) {\n"
" int mask_cols=mask_elements >= insert_len*kv_len ? kv_len : insert_len;\n"
" int gap=kv_len-mask_cols;\n"
" int col=k-gap;\n"
" int mask_index=q*mask_cols+col;\n"
" if (col >= 0 && col<mask_cols && mask_index >= 0 && mask_index<mask_elements) {\n"
" score += (float)mask[mask_index];\n"
" }\n"
" }\n"
" float weight=exp(score-max_score);\n"
" sum += weight;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" int v_offset=((b*kv_heads+kv_head)*max_slots+slot)*head_dim+d;\n"
" acc[d] += weight*(float)value_cache[v_offset];\n"
" }\n"
" }\n"
" float inv_sum=sum>0.0f ? 1.0f/sum : 0.0f;\n"
" for (int d=0; d<head_dim; ++d) {\n"
" output[((b*query_len+q)*num_heads+h)*head_dim+d]=(FLOAT)(acc[d]*inv_sum);\n"
" }\n"
"}\n"
"__kernel void paged_attention(\n"
" __global const FLOAT* query,\n"
" __global const FLOAT* key_cache,\n"
" __global const FLOAT* value_cache,\n"
" __global FLOAT* output,\n"
" __global const FLOAT* mask,\n"
" __global const int* slot_table,\n"
" __global const int* sparse_query,\n"
" const int mask_elements,\n"
" const int batch,\n"
" const int query_len,\n"
" const int insert_len,\n"
" const int num_heads,\n"
" const int kv_heads,\n"
" const int head_dim,\n"
" const int base_logical,\n"
" const int kv_len,\n"
" const int max_slots,\n"
" const float scale,\n"
" const int sparse_active,\n"
" const int total) {\n"
" int index=get_global_id(0);\n"
" if (index >= total) {\n"
" return;\n"
" }\n"
" int d=index % head_dim;\n"
" int t=index/head_dim;\n"
" int h=t % num_heads;\n"
" t=t/num_heads;\n"
" int q=t % insert_len;\n"
" int b=t/insert_len;\n"
" int group=num_heads/kv_heads;\n"
" int kv_head=h/group;\n"
" int q_logical=sparse_active ? sparse_query[q] : (base_logical+q);\n"
" int valid_len=min(kv_len,q_logical+1);\n"
" if (valid_len <= 0) {\n"
" output[((b*query_len+q)*num_heads+h)*head_dim+d]=(FLOAT)0;\n"
" return;\n"
" }\n"
" float max_score=-3.4028234663852886e+38f;\n"
" for (int k=0; k<valid_len; ++k) {\n"
" int slot=slot_table[k];\n"
" float score=0.0f;\n"
" for (int kd=0; kd<head_dim; ++kd) {\n"
" int q_offset=((b*query_len+q)*num_heads+h)*head_dim+kd;\n"
" int k_offset=((slot*batch+b)*kv_heads+kv_head)*head_dim+kd;\n"
" score += (float)query[q_offset]*(float)key_cache[k_offset];\n"
" }\n"
" score *= scale;\n"
" if (mask_elements>1) {\n"
" int mask_cols=mask_elements >= insert_len*kv_len ? kv_len : insert_len;\n"
" int gap=kv_len-mask_cols;\n"
" int col=k-gap;\n"
" int mask_index=q*mask_cols+col;\n"
" if (col >= 0 && col<mask_cols && mask_index >= 0 && mask_index<mask_elements) {\n"
" score += (float)mask[mask_index];\n"
" }\n"
" }\n"
" max_score=fmax(max_score,score);\n"
" }\n"
" float sum=0.0f;\n"
" float acc=0.0f;\n"
" for (int k=0; k<valid_len; ++k) {\n"
" int slot=slot_table[k];\n"
" float score=0.0f;\n"
" for (int kd=0; kd<head_dim; ++kd) {\n"
" int q_offset=((b*query_len+q)*num_heads+h)*head_dim+kd;\n"
" int k_offset=((slot*batch+b)*kv_heads+kv_head)*head_dim+kd;\n"
" score += (float)query[q_offset]*(float)key_cache[k_offset];\n"
" }\n"
" score *= scale;\n"
" if (mask_elements>1) {\n"
" int mask_cols=mask_elements >= insert_len*kv_len ? kv_len : insert_len;\n"
" int gap=kv_len-mask_cols;\n"
" int col=k-gap;\n"
" int mask_index=q*mask_cols+col;\n"
" if (col >= 0 && col<mask_cols && mask_index >= 0 && mask_index<mask_elements) {\n"
" score += (float)mask[mask_index];\n"
" }\n"
" }\n"
" float weight=exp(score-max_score);\n"
" int v_offset=((b*kv_heads+kv_head)*max_slots+slot)*head_dim+d;\n"
" acc += weight*(float)value_cache[v_offset];\n"
" sum += weight;\n"
" }\n"
" output[((b*query_len+q)*num_heads+h)*head_dim+d]=(FLOAT)(sum>0.0f ? acc/sum : 0.0f);\n"
"}\n"
;
#endif
}
