#include "opencl_source_map.hpp" 
namespace MNN { 
const char* sparse_flash_row_bench = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"#ifndef NUMHEAD_GROUP_SIZE\n"
"#define NUMHEAD_GROUP_SIZE 1\n"
"#endif\n"
"#define SPARSE_FLASH_MAX_HEAD_DIM8 16\n"
"__kernel void sparse_flash_attention_row64(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,// [batch head_num head_dim_4 query_seq_len_4]\n"
" __global const FLOAT *past_key,// [batch kv_head_num head_dim_4 kv_max_length]\n"
" __global const FLOAT *past_value,// [batch kv_head_num kv_max_length head_dim]\n"
" __global const int *sparse_query,// [query_seq_len]\n"
" __global FLOAT *output,// [batch query_seq_len head_num head_dim]\n"
" __private const float scale,\n"
" __private const int query_seq_len,\n"
" __private const int output_seq_len,\n"
" __private const int query_rows_are_full,\n"
" __private const int q_start,\n"
" __private const int q_piece_len,\n"
" __private const int key_seq_len,\n"
" __private const int key_max_len,\n"
" __private const int value_max_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // fixed 64 lanes\n"
" const int y=get_global_id(1); // q piece token\n"
" int z=get_global_id(2); // head_num*batch\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int lid=get_local_id(0);\n"
" const int head_dim8=head_dim >> 3;\n"
" if (get_local_size(0) != 64 || lid >= 64 || (head_dim != 64 && head_dim != 128) ||\n"
" head_dim8 <= 0 || head_dim8>SPARSE_FLASH_MAX_HEAD_DIM8) {\n"
" return;\n"
" }\n"
" const int q_index=q_start+y;\n"
" if (y >= q_piece_len || q_index >= output_seq_len) {\n"
" return;\n"
" }\n"
" const int b=z/head_num;\n"
" const int h=z-b*head_num;\n"
" const int kvh=h/NUMHEAD_GROUP_SIZE;\n"
" if (kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" const int query_seq_len4=(query_seq_len+3)/4*4;\n"
" const int q_logical=sparse_query[q_index];\n"
" const int q_row=query_rows_are_full ? q_logical : q_index;\n"
" if (q_row<0 || q_row >= query_seq_len) {\n"
" return;\n"
" }\n"
" const int active_kv_seq_len=clamp(q_logical+1,0,key_seq_len);\n"
" COMPUTE_FLOAT local local_m[64];\n"
" COMPUTE_FLOAT local local_l[64];\n"
" COMPUTE_FLOAT8 local local_o[64*SPARSE_FLASH_MAX_HEAD_DIM8];\n"
" COMPUTE_FLOAT8 o[SPARSE_FLASH_MAX_HEAD_DIM8];\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" o[d8]=(COMPUTE_FLOAT8)0;\n"
" }\n"
" COMPUTE_FLOAT m=(COMPUTE_FLOAT)-FLT_MAX;\n"
" COMPUTE_FLOAT l=(COMPUTE_FLOAT)0;\n"
" const int query_offset=z*head_dim*query_seq_len4+q_row;\n"
" const int key_base=(b*kv_head_num+kvh)*head_dim*key_max_len;\n"
" const int value_base=(b*kv_head_num+kvh)*value_max_len*head_dim;\n"
" for (int k=lid; k<active_kv_seq_len; k += 64) {\n"
" COMPUTE_FLOAT score=(COMPUTE_FLOAT)0;\n"
" for (int d4=0; d4<head_dim; d4 += 4) {\n"
" COMPUTE_FLOAT4 qv=CONVERT_COMPUTE_FLOAT4(vload4(0,query+query_offset+d4*query_seq_len4));\n"
" COMPUTE_FLOAT4 kv=CONVERT_COMPUTE_FLOAT4(vload4(0,past_key+key_base+d4*key_max_len+k));\n"
" score += dot(qv,kv);\n"
" }\n"
" score *= (COMPUTE_FLOAT)scale;\n"
" const COMPUTE_FLOAT new_m=fmax(m,score);\n"
" const COMPUTE_FLOAT alpha=l>(COMPUTE_FLOAT)0 ? exp(m-new_m) : (COMPUTE_FLOAT)0;\n"
" const COMPUTE_FLOAT beta=exp(score-new_m);\n"
" const int value_offset=value_base+k*head_dim;\n"
" const COMPUTE_FLOAT8 beta8=(COMPUTE_FLOAT8)beta;\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" o[d8]=o[d8]*alpha+beta8 *\n"
" CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+value_offset+(d8 << 3)));\n"
" }\n"
" l=l*alpha+beta;\n"
" m=new_m;\n"
" }\n"
" local_m[lid]=m;\n"
" local_l[lid]=l;\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" local_o[lid*SPARSE_FLASH_MAX_HEAD_DIM8+d8]=o[d8];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int stride=32; stride>0; stride >>= 1) {\n"
" if (lid<stride) {\n"
" const COMPUTE_FLOAT m0=local_m[lid];\n"
" const COMPUTE_FLOAT l0=local_l[lid];\n"
" const COMPUTE_FLOAT m1=local_m[lid+stride];\n"
" const COMPUTE_FLOAT l1=local_l[lid+stride];\n"
" const COMPUTE_FLOAT merged_m=fmax(m0,m1);\n"
" const COMPUTE_FLOAT a=l0>(COMPUTE_FLOAT)0 ? exp(m0-merged_m) : (COMPUTE_FLOAT)0;\n"
" const COMPUTE_FLOAT b_scale=l1>(COMPUTE_FLOAT)0 ? exp(m1-merged_m) : (COMPUTE_FLOAT)0;\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" local_o[lid*SPARSE_FLASH_MAX_HEAD_DIM8+d8] =\n"
" local_o[lid*SPARSE_FLASH_MAX_HEAD_DIM8+d8]*a +\n"
" local_o[(lid+stride)*SPARSE_FLASH_MAX_HEAD_DIM8+d8]*b_scale;\n"
" }\n"
" local_l[lid]=l0*a+l1*b_scale;\n"
" local_m[lid]=merged_m;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" const COMPUTE_FLOAT denom=local_l[0]>(COMPUTE_FLOAT)0 ? local_l[0] : (COMPUTE_FLOAT)1;\n"
" const int output_offset=((b*output_seq_len+q_index)*head_num+h)*head_dim;\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" vstore8(CONVERT_FLOAT8(local_o[d8]/(COMPUTE_FLOAT8)denom),0,\n"
" output+output_offset+(d8 << 3));\n"
" }\n"
" }\n"
"}\n"
"__kernel void sparse_flash_attention_row32(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,// [batch head_num head_dim_4 query_seq_len_4]\n"
" __global const FLOAT *past_key,// [batch kv_head_num head_dim_4 kv_max_length]\n"
" __global const FLOAT *past_value,// [batch kv_head_num kv_max_length head_dim]\n"
" __global const int *sparse_query,// [query_seq_len]\n"
" __global FLOAT *output,// [batch query_seq_len head_num head_dim]\n"
" __private const float scale,\n"
" __private const int query_seq_len,\n"
" __private const int output_seq_len,\n"
" __private const int query_rows_are_full,\n"
" __private const int q_start,\n"
" __private const int q_piece_len,\n"
" __private const int key_seq_len,\n"
" __private const int key_max_len,\n"
" __private const int value_max_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // fixed 32 lanes\n"
" const int y=get_global_id(1); // q piece token\n"
" int z=get_global_id(2); // head_num*batch\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int lid=get_local_id(0);\n"
" const int head_dim8=head_dim >> 3;\n"
" if (get_local_size(0) != 32 || lid >= 32 || (head_dim != 64 && head_dim != 128) ||\n"
" head_dim8 <= 0 || head_dim8>SPARSE_FLASH_MAX_HEAD_DIM8) {\n"
" return;\n"
" }\n"
" const int q_index=q_start+y;\n"
" if (y >= q_piece_len || q_index >= output_seq_len) {\n"
" return;\n"
" }\n"
" const int b=z/head_num;\n"
" const int h=z-b*head_num;\n"
" const int kvh=h/NUMHEAD_GROUP_SIZE;\n"
" if (kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" const int query_seq_len4=(query_seq_len+3)/4*4;\n"
" const int q_logical=sparse_query[q_index];\n"
" const int q_row=query_rows_are_full ? q_logical : q_index;\n"
" if (q_row<0 || q_row >= query_seq_len) {\n"
" return;\n"
" }\n"
" const int active_kv_seq_len=clamp(q_logical+1,0,key_seq_len);\n"
" COMPUTE_FLOAT local local_m[32];\n"
" COMPUTE_FLOAT local local_l[32];\n"
" COMPUTE_FLOAT8 local local_o[32*SPARSE_FLASH_MAX_HEAD_DIM8];\n"
" COMPUTE_FLOAT8 o[SPARSE_FLASH_MAX_HEAD_DIM8];\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" o[d8]=(COMPUTE_FLOAT8)0;\n"
" }\n"
" COMPUTE_FLOAT m=(COMPUTE_FLOAT)-FLT_MAX;\n"
" COMPUTE_FLOAT l=(COMPUTE_FLOAT)0;\n"
" const int query_offset=z*head_dim*query_seq_len4+q_row;\n"
" const int key_base=(b*kv_head_num+kvh)*head_dim*key_max_len;\n"
" const int value_base=(b*kv_head_num+kvh)*value_max_len*head_dim;\n"
" for (int k=lid; k<active_kv_seq_len; k += 32) {\n"
" COMPUTE_FLOAT score=(COMPUTE_FLOAT)0;\n"
" for (int d4=0; d4<head_dim; d4 += 4) {\n"
" COMPUTE_FLOAT4 qv=CONVERT_COMPUTE_FLOAT4(vload4(0,query+query_offset+d4*query_seq_len4));\n"
" COMPUTE_FLOAT4 kv=CONVERT_COMPUTE_FLOAT4(vload4(0,past_key+key_base+d4*key_max_len+k));\n"
" score += dot(qv,kv);\n"
" }\n"
" score *= (COMPUTE_FLOAT)scale;\n"
" const COMPUTE_FLOAT new_m=fmax(m,score);\n"
" const COMPUTE_FLOAT alpha=l>(COMPUTE_FLOAT)0 ? exp(m-new_m) : (COMPUTE_FLOAT)0;\n"
" const COMPUTE_FLOAT beta=exp(score-new_m);\n"
" const int value_offset=value_base+k*head_dim;\n"
" const COMPUTE_FLOAT8 beta8=(COMPUTE_FLOAT8)beta;\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" o[d8]=o[d8]*alpha+beta8 *\n"
" CONVERT_COMPUTE_FLOAT8(vload8(0,past_value+value_offset+(d8 << 3)));\n"
" }\n"
" l=l*alpha+beta;\n"
" m=new_m;\n"
" }\n"
" local_m[lid]=m;\n"
" local_l[lid]=l;\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" local_o[lid*SPARSE_FLASH_MAX_HEAD_DIM8+d8]=o[d8];\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int stride=16; stride>0; stride >>= 1) {\n"
" if (lid<stride) {\n"
" const COMPUTE_FLOAT m0=local_m[lid];\n"
" const COMPUTE_FLOAT l0=local_l[lid];\n"
" const COMPUTE_FLOAT m1=local_m[lid+stride];\n"
" const COMPUTE_FLOAT l1=local_l[lid+stride];\n"
" const COMPUTE_FLOAT merged_m=fmax(m0,m1);\n"
" const COMPUTE_FLOAT a=l0>(COMPUTE_FLOAT)0 ? exp(m0-merged_m) : (COMPUTE_FLOAT)0;\n"
" const COMPUTE_FLOAT b_scale=l1>(COMPUTE_FLOAT)0 ? exp(m1-merged_m) : (COMPUTE_FLOAT)0;\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" local_o[lid*SPARSE_FLASH_MAX_HEAD_DIM8+d8] =\n"
" local_o[lid*SPARSE_FLASH_MAX_HEAD_DIM8+d8]*a +\n"
" local_o[(lid+stride)*SPARSE_FLASH_MAX_HEAD_DIM8+d8]*b_scale;\n"
" }\n"
" local_l[lid]=l0*a+l1*b_scale;\n"
" local_m[lid]=merged_m;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (lid == 0) {\n"
" const COMPUTE_FLOAT denom=local_l[0]>(COMPUTE_FLOAT)0 ? local_l[0] : (COMPUTE_FLOAT)1;\n"
" const int output_offset=((b*output_seq_len+q_index)*head_num+h)*head_dim;\n"
" for (int d8=0; d8<head_dim8; ++d8) {\n"
" vstore8(CONVERT_FLOAT8(local_o[d8]/(COMPUTE_FLOAT8)denom),0,\n"
" output+output_offset+(d8 << 3));\n"
" }\n"
" }\n"
"}\n"
;
}
