#include "opencl_source_map.hpp" 
namespace MNN { 
const char* sparse_flash_row_probe_bench = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"#ifndef NUMHEAD_GROUP_SIZE\n"
"#define NUMHEAD_GROUP_SIZE 1\n"
"#endif\n"
"__kernel void sparse_flash_attention_row32_probe(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,\n"
" __global const FLOAT *past_key,\n"
" __global const FLOAT *past_value,\n"
" __global const int *sparse_query,\n"
" __global FLOAT *output,\n"
" __private const float scale,\n"
" __private const int query_seq_len,\n"
" __private const int output_seq_len,\n"
" __private const int query_rows_are_full,\n"
" __private const int q_start,\n"
" __private const int q_piece_len,\n"
" __private const int key_seq_len,\n"
" __private const int key_max_len,\n"
" __private const int value_max_len,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0);\n"
" const int y=get_global_id(1);\n"
" int z=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int lid=get_local_id(0);\n"
" if (get_local_size(0) != 32 || lid >= 32 || (head_dim != 64 && head_dim != 128)) {\n"
" return;\n"
" }\n"
" const int q_index=q_start+y;\n"
" if (y >= q_piece_len || q_index >= output_seq_len) {\n"
" return;\n"
" }\n"
" const int b=z/head_num;\n"
" const int h=z-b*head_num;\n"
" const int kvh=h/NUMHEAD_GROUP_SIZE;\n"
" if (kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" if (lid == 0) {\n"
" const int output_offset=((b*output_seq_len+q_index)*head_num+h)*head_dim;\n"
" for (int d8=0; d8<head_dim; d8 += 8) {\n"
" vstore8((FLOAT8)0,0,output+output_offset+d8);\n"
" }\n"
" }\n"
"}\n"
;
}
