#include "opencl_source_map.hpp" 
namespace MNN { 
const char* sparse_flash_qtile_kimg_bench = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "" if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "" return; "" }\n"
"#ifndef NUMHEAD_GROUP_SIZE\n"
"#define NUMHEAD_GROUP_SIZE 1\n"
"#endif\n"
"__constant sampler_t SPARSE_FLASH_IMAGE_SAMPLER =\n"
" CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;\n"
"inline FLOAT4 sparse_flash_read_linear4_image(__read_only image2d_t image,\n"
" const int linear_index,\n"
" const int image_width) {\n"
" const int pixel0=linear_index >> 2;\n"
" const int2 coord0=(int2)(pixel0-(pixel0/image_width)*image_width,pixel0/image_width);\n"
" const FLOAT4 p0=RI_F(image,SPARSE_FLASH_IMAGE_SAMPLER,coord0);\n"
" const int lane=linear_index & 3;\n"
" if (lane == 0) {\n"
" return p0;\n"
" }\n"
" const int pixel1=(linear_index+3) >> 2;\n"
" const int2 coord1=(int2)(pixel1-(pixel1/image_width)*image_width,pixel1/image_width);\n"
" const FLOAT4 p1=RI_F(image,SPARSE_FLASH_IMAGE_SAMPLER,coord1);\n"
" if (lane == 1) {\n"
" return (FLOAT4)(p0.y,p0.z,p0.w,p1.x);\n"
" }\n"
" if (lane == 2) {\n"
" return (FLOAT4)(p0.z,p0.w,p1.x,p1.y);\n"
" }\n"
" return (FLOAT4)(p0.w,p1.x,p1.y,p1.z);\n"
"}\n"
"#define MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE 8\n"
"#define MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE 16\n"
"#define MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES 16\n"
"#define MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE 4\n"
"#define MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE 8\n"
"#define MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES 16\n"
"__kernel void mqtile_sparse_flash_hd128_q4k8_kimg(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,// [batch head_num head_dim_4 query_seq_len_4]\n"
" __read_only image2d_t past_key_image,\n"
" __global const FLOAT *past_value,// [batch kv_head_num kv_max_length head_dim]\n"
" __global const int *sparse_query,// [query_seq_len]\n"
" __global FLOAT *output,// [batch query_seq_len head_num head_dim]\n"
" __private const float scale,\n"
" __private const int query_seq_len,\n"
" __private const int output_seq_len,\n"
" __private const int query_rows_are_full,\n"
" __private const int q_start,\n"
" __private const int q_piece_len,\n"
" __private const int key_seq_len,\n"
" __private const int key_max_len,\n"
" __private const int value_max_len,\n"
" __private const int key_image_width,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // fixed 16 dim lanes\n"
" const int y=get_global_id(1); // q piece token\n"
" int z=get_global_id(2); // head_num*batch\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int lane=get_local_id(0);\n"
" const int q_lane=get_local_id(1);\n"
" if (get_local_size(0) != MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES ||\n"
" get_local_size(1) != MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE ||\n"
" lane >= MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES ||\n"
" q_lane >= MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE ||\n"
" head_dim != 128) {\n"
" return;\n"
" }\n"
" const int q_tile_base=y-q_lane;\n"
" const int q_tile_valid_count=clamp(q_piece_len-q_tile_base,0,MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE);\n"
" if (q_tile_valid_count <= 0) {\n"
" return;\n"
" }\n"
" const int q_index=q_start+y;\n"
" const int q_valid=(q_lane<q_tile_valid_count && y<q_piece_len && q_index<output_seq_len) ? 1 : 0;\n"
" const int b=z/head_num;\n"
" const int h=z-b*head_num;\n"
" const int kvh=h/NUMHEAD_GROUP_SIZE;\n"
" if (kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" const int query_seq_len4=(query_seq_len+3)/4*4;\n"
" const int q_logical=q_valid ? sparse_query[q_index] : 0;\n"
" const int q_row=query_rows_are_full ? q_logical : q_index;\n"
" const int q_row_valid=q_valid && q_row >= 0 && q_row<query_seq_len;\n"
" int local q_tile_logical[MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE];\n"
" int local q_tile_min_logical;\n"
" int local q_tile_max_logical;\n"
" if (lane == 0) {\n"
" q_tile_logical[q_lane]=q_row_valid ? q_logical : -1;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane == 0 && q_lane == 0) {\n"
" int tile_min_logical=key_seq_len;\n"
" int tile_max_logical=-1;\n"
" for (int qi=0; qi<MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE; ++qi) {\n"
" const int logical=q_tile_logical[qi];\n"
" if (logical<0) {\n"
" continue;\n"
" }\n"
" tile_min_logical=min(tile_min_logical,logical);\n"
" tile_max_logical=max(tile_max_logical,logical);\n"
" }\n"
" q_tile_min_logical=tile_max_logical >= 0 ? tile_min_logical : -1;\n"
" q_tile_max_logical=tile_max_logical;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" const int active_kv_seq_len=q_tile_max_logical >= 0 ? clamp(q_tile_max_logical+1,0,key_seq_len) : 0;\n"
" COMPUTE_FLOAT local row_m[MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE];\n"
" COMPUTE_FLOAT local row_l[MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE];\n"
" COMPUTE_FLOAT local row_alpha[MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE];\n"
" COMPUTE_FLOAT local row_new_m[MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE];\n"
" COMPUTE_FLOAT local score_tile[MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE];\n"
" COMPUTE_FLOAT local beta_tile[MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE];\n"
" COMPUTE_FLOAT local partial_tile[MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE *\n"
" MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE *\n"
" MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES];\n"
" FLOAT4 local local_k0[MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES];\n"
" FLOAT4 local local_k1[MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES];\n"
" FLOAT8 local local_v[MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES];\n"
" if (lane == 0) {\n"
" row_m[q_lane]=(COMPUTE_FLOAT)-FLT_MAX;\n"
" row_l[q_lane]=(COMPUTE_FLOAT)0;\n"
" row_alpha[q_lane]=(COMPUTE_FLOAT)0;\n"
" row_new_m[q_lane]=(COMPUTE_FLOAT)-FLT_MAX;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" const int d_base=lane << 3;\n"
" const int query_base=z*head_dim*query_seq_len4+q_row;\n"
" const COMPUTE_FLOAT4 qv0=q_row_valid\n"
" ? CONVERT_COMPUTE_FLOAT4(vload4(0,query+query_base+d_base*query_seq_len4))\n"
" : (COMPUTE_FLOAT4)0;\n"
" const COMPUTE_FLOAT4 qv1=q_row_valid\n"
" ? CONVERT_COMPUTE_FLOAT4(vload4(0,query+query_base+(d_base+4)*query_seq_len4))\n"
" : (COMPUTE_FLOAT4)0;\n"
" COMPUTE_FLOAT8 out=(COMPUTE_FLOAT8)0;\n"
" const int key_base=(b*kv_head_num+kvh)*head_dim*key_max_len;\n"
" const int value_base=(b*kv_head_num+kvh)*value_max_len*head_dim;\n"
" const int linear_tid=q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES+lane;\n"
" for (int k_base=0; k_base<active_kv_seq_len; k_base += MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE) {\n"
" const int k_tile=min(MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE,active_kv_seq_len-k_base);\n"
" const int k_tile_end=k_base+k_tile-1;\n"
" const int k_tile_full=(q_tile_min_logical >= 0 && k_tile_end <= q_tile_min_logical) ? 1 : 0;\n"
" for (int load=linear_tid; load<k_tile*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES;\n"
" load += MQTILE_SPARSE_FLASH_HD128_Q4K8_QTILE*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES) {\n"
" const int k_local=load/MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES;\n"
" const int d_lane=load-k_local*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES;\n"
" const int dim=d_lane << 3;\n"
" const int k_index=k_base+k_local;\n"
" local_k0[k_local*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES+d_lane] =\n"
" sparse_flash_read_linear4_image(past_key_image,key_base+dim*key_max_len+k_index,\n"
" key_image_width);\n"
" local_k1[k_local*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES+d_lane] =\n"
" sparse_flash_read_linear4_image(past_key_image,key_base+(dim+4)*key_max_len+k_index,\n"
" key_image_width);\n"
" local_v[k_local*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES+d_lane] =\n"
" vload8(0,past_value+value_base+k_index*head_dim+dim);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int k_local=0; k_local<MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE; ++k_local) {\n"
" const int partial_index=((q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE+k_local) *\n"
" MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES)+lane;\n"
" COMPUTE_FLOAT partial=(COMPUTE_FLOAT)0;\n"
" if (q_row_valid && k_local<k_tile) {\n"
" const int k_index=k_base+k_local;\n"
" const int k_visible=k_tile_full || k_index <= q_logical;\n"
" if (k_visible) {\n"
" const COMPUTE_FLOAT4 kv0=CONVERT_COMPUTE_FLOAT4(\n"
" local_k0[k_local*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES+lane]);\n"
" const COMPUTE_FLOAT4 kv1=CONVERT_COMPUTE_FLOAT4(\n"
" local_k1[k_local*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES+lane]);\n"
" partial=dot(qv0,kv0)+dot(qv1,kv1);\n"
" }\n"
" }\n"
" partial_tile[partial_index]=partial;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane<MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE) {\n"
" COMPUTE_FLOAT score=(COMPUTE_FLOAT)-FLT_MAX;\n"
" if (q_row_valid && lane<k_tile) {\n"
" const int k_index=k_base+lane;\n"
" const int score_index=q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE+lane;\n"
" const int partial_base=score_index*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES;\n"
" if (k_tile_full || k_index <= q_logical) {\n"
" score=(COMPUTE_FLOAT)0;\n"
" for (int d_lane=0; d_lane<MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES; ++d_lane) {\n"
" score += partial_tile[partial_base+d_lane];\n"
" }\n"
" score *= (COMPUTE_FLOAT)scale;\n"
" }\n"
" }\n"
" score_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE+lane]=score;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane == 0) {\n"
" COMPUTE_FLOAT tile_max=(COMPUTE_FLOAT)-FLT_MAX;\n"
" if (q_row_valid) {\n"
" for (int k_local=0; k_local<k_tile; ++k_local) {\n"
" tile_max=fmax(tile_max,\n"
" score_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE+k_local]);\n"
" }\n"
" const COMPUTE_FLOAT merged_m=fmax(row_m[q_lane],tile_max);\n"
" row_alpha[q_lane]=row_l[q_lane]>(COMPUTE_FLOAT)0\n"
" ? exp(row_m[q_lane]-merged_m)\n"
" : (COMPUTE_FLOAT)0;\n"
" row_new_m[q_lane]=merged_m;\n"
" } else {\n"
" row_alpha[q_lane]=(COMPUTE_FLOAT)0;\n"
" row_new_m[q_lane]=(COMPUTE_FLOAT)-FLT_MAX;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane<MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE) {\n"
" COMPUTE_FLOAT beta=(COMPUTE_FLOAT)0;\n"
" if (q_row_valid && lane<k_tile) {\n"
" beta=exp(score_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE+lane]-row_new_m[q_lane]);\n"
" }\n"
" beta_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE+lane]=beta;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane == 0) {\n"
" COMPUTE_FLOAT tile_sum=(COMPUTE_FLOAT)0;\n"
" if (q_row_valid) {\n"
" for (int k_local=0; k_local<k_tile; ++k_local) {\n"
" tile_sum += beta_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE+k_local];\n"
" }\n"
" row_l[q_lane]=row_l[q_lane]*row_alpha[q_lane]+tile_sum;\n"
" row_m[q_lane]=row_new_m[q_lane];\n"
" } else {\n"
" row_l[q_lane]=(COMPUTE_FLOAT)0;\n"
" row_m[q_lane]=(COMPUTE_FLOAT)-FLT_MAX;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (q_row_valid) {\n"
" out *= (COMPUTE_FLOAT8)row_alpha[q_lane];\n"
" for (int k_local=0; k_local<k_tile; ++k_local) {\n"
" out += (COMPUTE_FLOAT8)beta_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q4K8_KTILE+k_local] *\n"
" CONVERT_COMPUTE_FLOAT8(local_v[k_local*MQTILE_SPARSE_FLASH_HD128_Q4K8_DLANES+lane]);\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (q_row_valid) {\n"
" const COMPUTE_FLOAT denom=row_l[q_lane]>(COMPUTE_FLOAT)0 ? row_l[q_lane] : (COMPUTE_FLOAT)1;\n"
" const int output_offset=((b*output_seq_len+q_index)*head_num+h)*head_dim+d_base;\n"
" vstore8(CONVERT_FLOAT8(out/(COMPUTE_FLOAT8)denom),0,output+output_offset);\n"
" }\n"
"}\n"
"__kernel void mqtile_sparse_flash_hd128_q8k16_kimg(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *query,// [batch head_num head_dim_4 query_seq_len_4]\n"
" __read_only image2d_t past_key_image,\n"
" __global const FLOAT *past_value,// [batch kv_head_num kv_max_length head_dim]\n"
" __global const int *sparse_query,// [query_seq_len]\n"
" __global FLOAT *output,// [batch query_seq_len head_num head_dim]\n"
" __private const float scale,\n"
" __private const int query_seq_len,\n"
" __private const int output_seq_len,\n"
" __private const int query_rows_are_full,\n"
" __private const int q_start,\n"
" __private const int q_piece_len,\n"
" __private const int key_seq_len,\n"
" __private const int key_max_len,\n"
" __private const int value_max_len,\n"
" __private const int key_image_width,\n"
" __private const int head_num,\n"
" __private const int kv_head_num,\n"
" __private const int head_dim) {\n"
" const int x=get_global_id(0); // fixed 16 dim lanes\n"
" const int y=get_global_id(1); // q piece token\n"
" int z=get_global_id(2); // head_num*batch\n"
" DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
" const int lane=get_local_id(0);\n"
" const int q_lane=get_local_id(1);\n"
" if (get_local_size(0) != MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES ||\n"
" get_local_size(1) != MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE ||\n"
" lane >= MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES ||\n"
" q_lane >= MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE ||\n"
" head_dim != 128) {\n"
" return;\n"
" }\n"
" const int q_tile_base=y-q_lane;\n"
" const int q_tile_valid_count=clamp(q_piece_len-q_tile_base,0,MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE);\n"
" if (q_tile_valid_count <= 0) {\n"
" return;\n"
" }\n"
" const int q_index=q_start+y;\n"
" const int q_valid=(q_lane<q_tile_valid_count && y<q_piece_len && q_index<output_seq_len) ? 1 : 0;\n"
" const int b=z/head_num;\n"
" const int h=z-b*head_num;\n"
" const int kvh=h/NUMHEAD_GROUP_SIZE;\n"
" if (kvh >= kv_head_num) {\n"
" return;\n"
" }\n"
" const int query_seq_len4=(query_seq_len+3)/4*4;\n"
" const int q_logical=q_valid ? sparse_query[q_index] : 0;\n"
" const int q_row=query_rows_are_full ? q_logical : q_index;\n"
" const int q_row_valid=q_valid && q_row >= 0 && q_row<query_seq_len;\n"
" int local q_tile_logical[MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE];\n"
" int local q_tile_min_logical;\n"
" int local q_tile_max_logical;\n"
" if (lane == 0) {\n"
" q_tile_logical[q_lane]=q_row_valid ? q_logical : -1;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane == 0 && q_lane == 0) {\n"
" int tile_min_logical=key_seq_len;\n"
" int tile_max_logical=-1;\n"
" for (int qi=0; qi<MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE; ++qi) {\n"
" const int logical=q_tile_logical[qi];\n"
" if (logical<0) {\n"
" continue;\n"
" }\n"
" tile_min_logical=min(tile_min_logical,logical);\n"
" tile_max_logical=max(tile_max_logical,logical);\n"
" }\n"
" q_tile_min_logical=tile_max_logical >= 0 ? tile_min_logical : -1;\n"
" q_tile_max_logical=tile_max_logical;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" const int active_kv_seq_len=q_tile_max_logical >= 0 ? clamp(q_tile_max_logical+1,0,key_seq_len) : 0;\n"
" COMPUTE_FLOAT local row_m[MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE];\n"
" COMPUTE_FLOAT local row_l[MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE];\n"
" COMPUTE_FLOAT local row_alpha[MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE];\n"
" COMPUTE_FLOAT local row_new_m[MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE];\n"
" COMPUTE_FLOAT local score_tile[MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE];\n"
" COMPUTE_FLOAT local beta_tile[MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE];\n"
" COMPUTE_FLOAT local partial_tile[MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE *\n"
" MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE *\n"
" MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES];\n"
" FLOAT4 local local_k0[MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES];\n"
" FLOAT4 local local_k1[MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES];\n"
" FLOAT8 local local_v[MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES];\n"
" if (lane == 0) {\n"
" row_m[q_lane]=(COMPUTE_FLOAT)-FLT_MAX;\n"
" row_l[q_lane]=(COMPUTE_FLOAT)0;\n"
" row_alpha[q_lane]=(COMPUTE_FLOAT)0;\n"
" row_new_m[q_lane]=(COMPUTE_FLOAT)-FLT_MAX;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" const int d_base=lane << 3;\n"
" const int query_base=z*head_dim*query_seq_len4+q_row;\n"
" const COMPUTE_FLOAT4 qv0=q_row_valid\n"
" ? CONVERT_COMPUTE_FLOAT4(vload4(0,query+query_base+d_base*query_seq_len4))\n"
" : (COMPUTE_FLOAT4)0;\n"
" const COMPUTE_FLOAT4 qv1=q_row_valid\n"
" ? CONVERT_COMPUTE_FLOAT4(vload4(0,query+query_base+(d_base+4)*query_seq_len4))\n"
" : (COMPUTE_FLOAT4)0;\n"
" COMPUTE_FLOAT8 out=(COMPUTE_FLOAT8)0;\n"
" const int key_base=(b*kv_head_num+kvh)*head_dim*key_max_len;\n"
" const int value_base=(b*kv_head_num+kvh)*value_max_len*head_dim;\n"
" const int linear_tid=q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES+lane;\n"
" for (int k_base=0; k_base<active_kv_seq_len; k_base += MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE) {\n"
" const int k_tile=min(MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE,active_kv_seq_len-k_base);\n"
" const int k_tile_end=k_base+k_tile-1;\n"
" const int k_tile_full=(q_tile_min_logical >= 0 && k_tile_end <= q_tile_min_logical) ? 1 : 0;\n"
" for (int load=linear_tid; load<k_tile*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES;\n"
" load += MQTILE_SPARSE_FLASH_HD128_Q8K16_QTILE*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES) {\n"
" const int k_local=load/MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES;\n"
" const int d_lane=load-k_local*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES;\n"
" const int dim=d_lane << 3;\n"
" const int k_index=k_base+k_local;\n"
" local_k0[k_local*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES+d_lane] =\n"
" sparse_flash_read_linear4_image(past_key_image,key_base+dim*key_max_len+k_index,\n"
" key_image_width);\n"
" local_k1[k_local*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES+d_lane] =\n"
" sparse_flash_read_linear4_image(past_key_image,key_base+(dim+4)*key_max_len+k_index,\n"
" key_image_width);\n"
" local_v[k_local*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES+d_lane] =\n"
" vload8(0,past_value+value_base+k_index*head_dim+dim);\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for (int k_local=0; k_local<MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE; ++k_local) {\n"
" const int partial_index=((q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE+k_local) *\n"
" MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES)+lane;\n"
" COMPUTE_FLOAT partial=(COMPUTE_FLOAT)0;\n"
" if (q_row_valid && k_local<k_tile) {\n"
" const int k_index=k_base+k_local;\n"
" const int k_visible=k_tile_full || k_index <= q_logical;\n"
" if (k_visible) {\n"
" const COMPUTE_FLOAT4 kv0=CONVERT_COMPUTE_FLOAT4(\n"
" local_k0[k_local*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES+lane]);\n"
" const COMPUTE_FLOAT4 kv1=CONVERT_COMPUTE_FLOAT4(\n"
" local_k1[k_local*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES+lane]);\n"
" partial=dot(qv0,kv0)+dot(qv1,kv1);\n"
" }\n"
" }\n"
" partial_tile[partial_index]=partial;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane<MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE) {\n"
" COMPUTE_FLOAT score=(COMPUTE_FLOAT)-FLT_MAX;\n"
" if (q_row_valid && lane<k_tile) {\n"
" const int k_index=k_base+lane;\n"
" const int score_index=q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE+lane;\n"
" const int partial_base=score_index*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES;\n"
" if (k_tile_full || k_index <= q_logical) {\n"
" score=(COMPUTE_FLOAT)0;\n"
" for (int d_lane=0; d_lane<MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES; ++d_lane) {\n"
" score += partial_tile[partial_base+d_lane];\n"
" }\n"
" score *= (COMPUTE_FLOAT)scale;\n"
" }\n"
" }\n"
" score_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE+lane]=score;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane == 0) {\n"
" COMPUTE_FLOAT tile_max=(COMPUTE_FLOAT)-FLT_MAX;\n"
" if (q_row_valid) {\n"
" for (int k_local=0; k_local<k_tile; ++k_local) {\n"
" tile_max=fmax(tile_max,\n"
" score_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE+k_local]);\n"
" }\n"
" const COMPUTE_FLOAT merged_m=fmax(row_m[q_lane],tile_max);\n"
" row_alpha[q_lane]=row_l[q_lane]>(COMPUTE_FLOAT)0\n"
" ? exp(row_m[q_lane]-merged_m)\n"
" : (COMPUTE_FLOAT)0;\n"
" row_new_m[q_lane]=merged_m;\n"
" } else {\n"
" row_alpha[q_lane]=(COMPUTE_FLOAT)0;\n"
" row_new_m[q_lane]=(COMPUTE_FLOAT)-FLT_MAX;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane<MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE) {\n"
" COMPUTE_FLOAT beta=(COMPUTE_FLOAT)0;\n"
" if (q_row_valid && lane<k_tile) {\n"
" beta=exp(score_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE+lane]-row_new_m[q_lane]);\n"
" }\n"
" beta_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE+lane]=beta;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (lane == 0) {\n"
" COMPUTE_FLOAT tile_sum=(COMPUTE_FLOAT)0;\n"
" if (q_row_valid) {\n"
" for (int k_local=0; k_local<k_tile; ++k_local) {\n"
" tile_sum += beta_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE+k_local];\n"
" }\n"
" row_l[q_lane]=row_l[q_lane]*row_alpha[q_lane]+tile_sum;\n"
" row_m[q_lane]=row_new_m[q_lane];\n"
" } else {\n"
" row_l[q_lane]=(COMPUTE_FLOAT)0;\n"
" row_m[q_lane]=(COMPUTE_FLOAT)-FLT_MAX;\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" if (q_row_valid) {\n"
" out *= (COMPUTE_FLOAT8)row_alpha[q_lane];\n"
" for (int k_local=0; k_local<k_tile; ++k_local) {\n"
" out += (COMPUTE_FLOAT8)beta_tile[q_lane*MQTILE_SPARSE_FLASH_HD128_Q8K16_KTILE+k_local] *\n"
" CONVERT_COMPUTE_FLOAT8(local_v[k_local*MQTILE_SPARSE_FLASH_HD128_Q8K16_DLANES+lane]);\n"
" }\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" if (q_row_valid) {\n"
" const COMPUTE_FLOAT denom=row_l[q_lane]>(COMPUTE_FLOAT)0 ? row_l[q_lane] : (COMPUTE_FLOAT)1;\n"
" const int output_offset=((b*output_seq_len+q_index)*head_num+h)*head_dim+d_base;\n"
" vstore8(CONVERT_FLOAT8(out/(COMPUTE_FLOAT8)denom),0,output+output_offset);\n"
" }\n"
"}\n"
;
}
